// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker/broker.proto

package ProtobufBroker

import (
	stream "code.cryptowat.ch/cw-sdk-go/proto/stream"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BrokerSessionMessage struct {
	// Types that are valid to be assigned to SessionConfig:
	//	*BrokerSessionMessage_Session_
	//	*BrokerSessionMessage_AnonymousTradingSession_
	SessionConfig        isBrokerSessionMessage_SessionConfig `protobuf_oneof:"SessionConfig"`
	MarketId             int64                                `protobuf:"varint,3,opt,name=marketId,proto3" json:"marketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *BrokerSessionMessage) Reset()         { *m = BrokerSessionMessage{} }
func (m *BrokerSessionMessage) String() string { return proto.CompactTextString(m) }
func (*BrokerSessionMessage) ProtoMessage()    {}
func (*BrokerSessionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{0}
}

func (m *BrokerSessionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerSessionMessage.Unmarshal(m, b)
}
func (m *BrokerSessionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerSessionMessage.Marshal(b, m, deterministic)
}
func (m *BrokerSessionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerSessionMessage.Merge(m, src)
}
func (m *BrokerSessionMessage) XXX_Size() int {
	return xxx_messageInfo_BrokerSessionMessage.Size(m)
}
func (m *BrokerSessionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerSessionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerSessionMessage proto.InternalMessageInfo

type isBrokerSessionMessage_SessionConfig interface {
	isBrokerSessionMessage_SessionConfig()
}

type BrokerSessionMessage_Session_ struct {
	Session *BrokerSessionMessage_Session `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type BrokerSessionMessage_AnonymousTradingSession_ struct {
	AnonymousTradingSession *BrokerSessionMessage_AnonymousTradingSession `protobuf:"bytes,2,opt,name=anonymousTradingSession,proto3,oneof"`
}

func (*BrokerSessionMessage_Session_) isBrokerSessionMessage_SessionConfig() {}

func (*BrokerSessionMessage_AnonymousTradingSession_) isBrokerSessionMessage_SessionConfig() {}

func (m *BrokerSessionMessage) GetSessionConfig() isBrokerSessionMessage_SessionConfig {
	if m != nil {
		return m.SessionConfig
	}
	return nil
}

func (m *BrokerSessionMessage) GetSession() *BrokerSessionMessage_Session {
	if x, ok := m.GetSessionConfig().(*BrokerSessionMessage_Session_); ok {
		return x.Session
	}
	return nil
}

func (m *BrokerSessionMessage) GetAnonymousTradingSession() *BrokerSessionMessage_AnonymousTradingSession {
	if x, ok := m.GetSessionConfig().(*BrokerSessionMessage_AnonymousTradingSession_); ok {
		return x.AnonymousTradingSession
	}
	return nil
}

func (m *BrokerSessionMessage) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BrokerSessionMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BrokerSessionMessage_OneofMarshaler, _BrokerSessionMessage_OneofUnmarshaler, _BrokerSessionMessage_OneofSizer, []interface{}{
		(*BrokerSessionMessage_Session_)(nil),
		(*BrokerSessionMessage_AnonymousTradingSession_)(nil),
	}
}

func _BrokerSessionMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BrokerSessionMessage)
	// SessionConfig
	switch x := m.SessionConfig.(type) {
	case *BrokerSessionMessage_Session_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Session); err != nil {
			return err
		}
	case *BrokerSessionMessage_AnonymousTradingSession_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AnonymousTradingSession); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BrokerSessionMessage.SessionConfig has unexpected type %T", x)
	}
	return nil
}

func _BrokerSessionMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BrokerSessionMessage)
	switch tag {
	case 1: // SessionConfig.session
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BrokerSessionMessage_Session)
		err := b.DecodeMessage(msg)
		m.SessionConfig = &BrokerSessionMessage_Session_{msg}
		return true, err
	case 2: // SessionConfig.anonymousTradingSession
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BrokerSessionMessage_AnonymousTradingSession)
		err := b.DecodeMessage(msg)
		m.SessionConfig = &BrokerSessionMessage_AnonymousTradingSession_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BrokerSessionMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BrokerSessionMessage)
	// SessionConfig
	switch x := m.SessionConfig.(type) {
	case *BrokerSessionMessage_Session_:
		s := proto.Size(x.Session)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerSessionMessage_AnonymousTradingSession_:
		s := proto.Size(x.AnonymousTradingSession)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BrokerSessionMessage_Session struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Expires              int64    `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	MfaToken             string   `protobuf:"bytes,4,opt,name=mfaToken,proto3" json:"mfaToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerSessionMessage_Session) Reset()         { *m = BrokerSessionMessage_Session{} }
func (m *BrokerSessionMessage_Session) String() string { return proto.CompactTextString(m) }
func (*BrokerSessionMessage_Session) ProtoMessage()    {}
func (*BrokerSessionMessage_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{0, 0}
}

func (m *BrokerSessionMessage_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerSessionMessage_Session.Unmarshal(m, b)
}
func (m *BrokerSessionMessage_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerSessionMessage_Session.Marshal(b, m, deterministic)
}
func (m *BrokerSessionMessage_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerSessionMessage_Session.Merge(m, src)
}
func (m *BrokerSessionMessage_Session) XXX_Size() int {
	return xxx_messageInfo_BrokerSessionMessage_Session.Size(m)
}
func (m *BrokerSessionMessage_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerSessionMessage_Session.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerSessionMessage_Session proto.InternalMessageInfo

func (m *BrokerSessionMessage_Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BrokerSessionMessage_Session) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *BrokerSessionMessage_Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BrokerSessionMessage_Session) GetMfaToken() string {
	if m != nil {
		return m.MfaToken
	}
	return ""
}

type BrokerSessionMessage_AnonymousTradingSession struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           int64    `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerSessionMessage_AnonymousTradingSession) Reset() {
	*m = BrokerSessionMessage_AnonymousTradingSession{}
}
func (m *BrokerSessionMessage_AnonymousTradingSession) String() string {
	return proto.CompactTextString(m)
}
func (*BrokerSessionMessage_AnonymousTradingSession) ProtoMessage() {}
func (*BrokerSessionMessage_AnonymousTradingSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{0, 1}
}

func (m *BrokerSessionMessage_AnonymousTradingSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession.Unmarshal(m, b)
}
func (m *BrokerSessionMessage_AnonymousTradingSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession.Marshal(b, m, deterministic)
}
func (m *BrokerSessionMessage_AnonymousTradingSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession.Merge(m, src)
}
func (m *BrokerSessionMessage_AnonymousTradingSession) XXX_Size() int {
	return xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession.Size(m)
}
func (m *BrokerSessionMessage_AnonymousTradingSession) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerSessionMessage_AnonymousTradingSession proto.InternalMessageInfo

func (m *BrokerSessionMessage_AnonymousTradingSession) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *BrokerSessionMessage_AnonymousTradingSession) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BrokerSessionMessage_AnonymousTradingSession) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type PlaceOrderRequest struct {
	Order                *PrivateOrder `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	ClosingOrder         *PrivateOrder `protobuf:"bytes,3,opt,name=closingOrder,proto3" json:"closingOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{1}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetOrder() *PrivateOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *PlaceOrderRequest) GetClosingOrder() *PrivateOrder {
	if m != nil {
		return m.ClosingOrder
	}
	return nil
}

type PlaceOrderResult struct {
	Order *PrivateOrder `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// Deprecated
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResult) Reset()         { *m = PlaceOrderResult{} }
func (m *PlaceOrderResult) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResult) ProtoMessage()    {}
func (*PlaceOrderResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{2}
}

func (m *PlaceOrderResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResult.Unmarshal(m, b)
}
func (m *PlaceOrderResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResult.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResult.Merge(m, src)
}
func (m *PlaceOrderResult) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResult.Size(m)
}
func (m *PlaceOrderResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResult.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResult proto.InternalMessageInfo

func (m *PlaceOrderResult) GetOrder() *PrivateOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *PlaceOrderResult) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type CancelOrderRequest struct {
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{3}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type CancelOrderResult struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResult) Reset()         { *m = CancelOrderResult{} }
func (m *CancelOrderResult) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResult) ProtoMessage()    {}
func (*CancelOrderResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{4}
}

func (m *CancelOrderResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResult.Unmarshal(m, b)
}
func (m *CancelOrderResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResult.Marshal(b, m, deterministic)
}
func (m *CancelOrderResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResult.Merge(m, src)
}
func (m *CancelOrderResult) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResult.Size(m)
}
func (m *CancelOrderResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResult.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResult proto.InternalMessageInfo

func (m *CancelOrderResult) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type ReplaceOrderRequest struct {
	OrderId                 string        `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Replacement             *PrivateOrder `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	ReplacementClosingOrder *PrivateOrder `protobuf:"bytes,3,opt,name=replacementClosingOrder,proto3" json:"replacementClosingOrder,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *ReplaceOrderRequest) Reset()         { *m = ReplaceOrderRequest{} }
func (m *ReplaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceOrderRequest) ProtoMessage()    {}
func (*ReplaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{5}
}

func (m *ReplaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceOrderRequest.Unmarshal(m, b)
}
func (m *ReplaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceOrderRequest.Merge(m, src)
}
func (m *ReplaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceOrderRequest.Size(m)
}
func (m *ReplaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceOrderRequest proto.InternalMessageInfo

func (m *ReplaceOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ReplaceOrderRequest) GetReplacement() *PrivateOrder {
	if m != nil {
		return m.Replacement
	}
	return nil
}

func (m *ReplaceOrderRequest) GetReplacementClosingOrder() *PrivateOrder {
	if m != nil {
		return m.ReplacementClosingOrder
	}
	return nil
}

type ClosePositionRequest struct {
	PositionId           string   `protobuf:"bytes,2,opt,name=positionId,proto3" json:"positionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosePositionRequest) Reset()         { *m = ClosePositionRequest{} }
func (m *ClosePositionRequest) String() string { return proto.CompactTextString(m) }
func (*ClosePositionRequest) ProtoMessage()    {}
func (*ClosePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{6}
}

func (m *ClosePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosePositionRequest.Unmarshal(m, b)
}
func (m *ClosePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosePositionRequest.Marshal(b, m, deterministic)
}
func (m *ClosePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosePositionRequest.Merge(m, src)
}
func (m *ClosePositionRequest) XXX_Size() int {
	return xxx_messageInfo_ClosePositionRequest.Size(m)
}
func (m *ClosePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClosePositionRequest proto.InternalMessageInfo

func (m *ClosePositionRequest) GetPositionId() string {
	if m != nil {
		return m.PositionId
	}
	return ""
}

type SyncRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{7}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

type BrokerRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// marketId can be 0 if there is just one session associated with the
	// connection.
	MarketId int64 `protobuf:"varint,7,opt,name=marketId,proto3" json:"marketId,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*BrokerRequest_PlaceOrderRequest
	//	*BrokerRequest_CancelOrderRequest
	//	*BrokerRequest_ReplaceOrderRequest
	//	*BrokerRequest_SyncRequest
	//	*BrokerRequest_ClosePositionRequest
	Request              isBrokerRequest_Request `protobuf_oneof:"Request"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BrokerRequest) Reset()         { *m = BrokerRequest{} }
func (m *BrokerRequest) String() string { return proto.CompactTextString(m) }
func (*BrokerRequest) ProtoMessage()    {}
func (*BrokerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{8}
}

func (m *BrokerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerRequest.Unmarshal(m, b)
}
func (m *BrokerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerRequest.Marshal(b, m, deterministic)
}
func (m *BrokerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerRequest.Merge(m, src)
}
func (m *BrokerRequest) XXX_Size() int {
	return xxx_messageInfo_BrokerRequest.Size(m)
}
func (m *BrokerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerRequest proto.InternalMessageInfo

func (m *BrokerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BrokerRequest) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

type isBrokerRequest_Request interface {
	isBrokerRequest_Request()
}

type BrokerRequest_PlaceOrderRequest struct {
	PlaceOrderRequest *PlaceOrderRequest `protobuf:"bytes,2,opt,name=placeOrderRequest,proto3,oneof"`
}

type BrokerRequest_CancelOrderRequest struct {
	CancelOrderRequest *CancelOrderRequest `protobuf:"bytes,3,opt,name=cancelOrderRequest,proto3,oneof"`
}

type BrokerRequest_ReplaceOrderRequest struct {
	ReplaceOrderRequest *ReplaceOrderRequest `protobuf:"bytes,6,opt,name=replaceOrderRequest,proto3,oneof"`
}

type BrokerRequest_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,4,opt,name=syncRequest,proto3,oneof"`
}

type BrokerRequest_ClosePositionRequest struct {
	ClosePositionRequest *ClosePositionRequest `protobuf:"bytes,5,opt,name=closePositionRequest,proto3,oneof"`
}

func (*BrokerRequest_PlaceOrderRequest) isBrokerRequest_Request() {}

func (*BrokerRequest_CancelOrderRequest) isBrokerRequest_Request() {}

func (*BrokerRequest_ReplaceOrderRequest) isBrokerRequest_Request() {}

func (*BrokerRequest_SyncRequest) isBrokerRequest_Request() {}

func (*BrokerRequest_ClosePositionRequest) isBrokerRequest_Request() {}

func (m *BrokerRequest) GetRequest() isBrokerRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *BrokerRequest) GetPlaceOrderRequest() *PlaceOrderRequest {
	if x, ok := m.GetRequest().(*BrokerRequest_PlaceOrderRequest); ok {
		return x.PlaceOrderRequest
	}
	return nil
}

func (m *BrokerRequest) GetCancelOrderRequest() *CancelOrderRequest {
	if x, ok := m.GetRequest().(*BrokerRequest_CancelOrderRequest); ok {
		return x.CancelOrderRequest
	}
	return nil
}

func (m *BrokerRequest) GetReplaceOrderRequest() *ReplaceOrderRequest {
	if x, ok := m.GetRequest().(*BrokerRequest_ReplaceOrderRequest); ok {
		return x.ReplaceOrderRequest
	}
	return nil
}

func (m *BrokerRequest) GetSyncRequest() *SyncRequest {
	if x, ok := m.GetRequest().(*BrokerRequest_SyncRequest); ok {
		return x.SyncRequest
	}
	return nil
}

func (m *BrokerRequest) GetClosePositionRequest() *ClosePositionRequest {
	if x, ok := m.GetRequest().(*BrokerRequest_ClosePositionRequest); ok {
		return x.ClosePositionRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BrokerRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BrokerRequest_OneofMarshaler, _BrokerRequest_OneofUnmarshaler, _BrokerRequest_OneofSizer, []interface{}{
		(*BrokerRequest_PlaceOrderRequest)(nil),
		(*BrokerRequest_CancelOrderRequest)(nil),
		(*BrokerRequest_ReplaceOrderRequest)(nil),
		(*BrokerRequest_SyncRequest)(nil),
		(*BrokerRequest_ClosePositionRequest)(nil),
	}
}

func _BrokerRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BrokerRequest)
	// Request
	switch x := m.Request.(type) {
	case *BrokerRequest_PlaceOrderRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlaceOrderRequest); err != nil {
			return err
		}
	case *BrokerRequest_CancelOrderRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancelOrderRequest); err != nil {
			return err
		}
	case *BrokerRequest_ReplaceOrderRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplaceOrderRequest); err != nil {
			return err
		}
	case *BrokerRequest_SyncRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SyncRequest); err != nil {
			return err
		}
	case *BrokerRequest_ClosePositionRequest:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClosePositionRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BrokerRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _BrokerRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BrokerRequest)
	switch tag {
	case 2: // Request.placeOrderRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlaceOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &BrokerRequest_PlaceOrderRequest{msg}
		return true, err
	case 3: // Request.cancelOrderRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancelOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &BrokerRequest_CancelOrderRequest{msg}
		return true, err
	case 6: // Request.replaceOrderRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplaceOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &BrokerRequest_ReplaceOrderRequest{msg}
		return true, err
	case 4: // Request.syncRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SyncRequest)
		err := b.DecodeMessage(msg)
		m.Request = &BrokerRequest_SyncRequest{msg}
		return true, err
	case 5: // Request.closePositionRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClosePositionRequest)
		err := b.DecodeMessage(msg)
		m.Request = &BrokerRequest_ClosePositionRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BrokerRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BrokerRequest)
	// Request
	switch x := m.Request.(type) {
	case *BrokerRequest_PlaceOrderRequest:
		s := proto.Size(x.PlaceOrderRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerRequest_CancelOrderRequest:
		s := proto.Size(x.CancelOrderRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerRequest_ReplaceOrderRequest:
		s := proto.Size(x.ReplaceOrderRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerRequest_SyncRequest:
		s := proto.Size(x.SyncRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerRequest_ClosePositionRequest:
		s := proto.Size(x.ClosePositionRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OrdersUpdate struct {
	Orders               []*PrivateOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrdersUpdate) Reset()         { *m = OrdersUpdate{} }
func (m *OrdersUpdate) String() string { return proto.CompactTextString(m) }
func (*OrdersUpdate) ProtoMessage()    {}
func (*OrdersUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{9}
}

func (m *OrdersUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersUpdate.Unmarshal(m, b)
}
func (m *OrdersUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersUpdate.Marshal(b, m, deterministic)
}
func (m *OrdersUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersUpdate.Merge(m, src)
}
func (m *OrdersUpdate) XXX_Size() int {
	return xxx_messageInfo_OrdersUpdate.Size(m)
}
func (m *OrdersUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersUpdate proto.InternalMessageInfo

func (m *OrdersUpdate) GetOrders() []*PrivateOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type TradesUpdate struct {
	Trades               []*PrivateTrade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TradesUpdate) Reset()         { *m = TradesUpdate{} }
func (m *TradesUpdate) String() string { return proto.CompactTextString(m) }
func (*TradesUpdate) ProtoMessage()    {}
func (*TradesUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{10}
}

func (m *TradesUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesUpdate.Unmarshal(m, b)
}
func (m *TradesUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesUpdate.Marshal(b, m, deterministic)
}
func (m *TradesUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesUpdate.Merge(m, src)
}
func (m *TradesUpdate) XXX_Size() int {
	return xxx_messageInfo_TradesUpdate.Size(m)
}
func (m *TradesUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TradesUpdate proto.InternalMessageInfo

func (m *TradesUpdate) GetTrades() []*PrivateTrade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type PositionsUpdate struct {
	Positions            []*PrivatePosition `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PositionsUpdate) Reset()         { *m = PositionsUpdate{} }
func (m *PositionsUpdate) String() string { return proto.CompactTextString(m) }
func (*PositionsUpdate) ProtoMessage()    {}
func (*PositionsUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{11}
}

func (m *PositionsUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionsUpdate.Unmarshal(m, b)
}
func (m *PositionsUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionsUpdate.Marshal(b, m, deterministic)
}
func (m *PositionsUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionsUpdate.Merge(m, src)
}
func (m *PositionsUpdate) XXX_Size() int {
	return xxx_messageInfo_PositionsUpdate.Size(m)
}
func (m *PositionsUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionsUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PositionsUpdate proto.InternalMessageInfo

func (m *PositionsUpdate) GetPositions() []*PrivatePosition {
	if m != nil {
		return m.Positions
	}
	return nil
}

type BalancesUpdate struct {
	Balances             []*Balances `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BalancesUpdate) Reset()         { *m = BalancesUpdate{} }
func (m *BalancesUpdate) String() string { return proto.CompactTextString(m) }
func (*BalancesUpdate) ProtoMessage()    {}
func (*BalancesUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{12}
}

func (m *BalancesUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancesUpdate.Unmarshal(m, b)
}
func (m *BalancesUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancesUpdate.Marshal(b, m, deterministic)
}
func (m *BalancesUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancesUpdate.Merge(m, src)
}
func (m *BalancesUpdate) XXX_Size() int {
	return xxx_messageInfo_BalancesUpdate.Size(m)
}
func (m *BalancesUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancesUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_BalancesUpdate proto.InternalMessageInfo

func (m *BalancesUpdate) GetBalances() []*Balances {
	if m != nil {
		return m.Balances
	}
	return nil
}

type RequestResolutionUpdate struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error   int32  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*RequestResolutionUpdate_PlaceOrderResult
	//	*RequestResolutionUpdate_CancelOrderResult
	Result               isRequestResolutionUpdate_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *RequestResolutionUpdate) Reset()         { *m = RequestResolutionUpdate{} }
func (m *RequestResolutionUpdate) String() string { return proto.CompactTextString(m) }
func (*RequestResolutionUpdate) ProtoMessage()    {}
func (*RequestResolutionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{13}
}

func (m *RequestResolutionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResolutionUpdate.Unmarshal(m, b)
}
func (m *RequestResolutionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResolutionUpdate.Marshal(b, m, deterministic)
}
func (m *RequestResolutionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResolutionUpdate.Merge(m, src)
}
func (m *RequestResolutionUpdate) XXX_Size() int {
	return xxx_messageInfo_RequestResolutionUpdate.Size(m)
}
func (m *RequestResolutionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResolutionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResolutionUpdate proto.InternalMessageInfo

func (m *RequestResolutionUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RequestResolutionUpdate) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *RequestResolutionUpdate) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isRequestResolutionUpdate_Result interface {
	isRequestResolutionUpdate_Result()
}

type RequestResolutionUpdate_PlaceOrderResult struct {
	PlaceOrderResult *PlaceOrderResult `protobuf:"bytes,4,opt,name=placeOrderResult,proto3,oneof"`
}

type RequestResolutionUpdate_CancelOrderResult struct {
	CancelOrderResult *CancelOrderResult `protobuf:"bytes,5,opt,name=cancelOrderResult,proto3,oneof"`
}

func (*RequestResolutionUpdate_PlaceOrderResult) isRequestResolutionUpdate_Result() {}

func (*RequestResolutionUpdate_CancelOrderResult) isRequestResolutionUpdate_Result() {}

func (m *RequestResolutionUpdate) GetResult() isRequestResolutionUpdate_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RequestResolutionUpdate) GetPlaceOrderResult() *PlaceOrderResult {
	if x, ok := m.GetResult().(*RequestResolutionUpdate_PlaceOrderResult); ok {
		return x.PlaceOrderResult
	}
	return nil
}

func (m *RequestResolutionUpdate) GetCancelOrderResult() *CancelOrderResult {
	if x, ok := m.GetResult().(*RequestResolutionUpdate_CancelOrderResult); ok {
		return x.CancelOrderResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RequestResolutionUpdate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RequestResolutionUpdate_OneofMarshaler, _RequestResolutionUpdate_OneofUnmarshaler, _RequestResolutionUpdate_OneofSizer, []interface{}{
		(*RequestResolutionUpdate_PlaceOrderResult)(nil),
		(*RequestResolutionUpdate_CancelOrderResult)(nil),
	}
}

func _RequestResolutionUpdate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RequestResolutionUpdate)
	// Result
	switch x := m.Result.(type) {
	case *RequestResolutionUpdate_PlaceOrderResult:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlaceOrderResult); err != nil {
			return err
		}
	case *RequestResolutionUpdate_CancelOrderResult:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancelOrderResult); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RequestResolutionUpdate.Result has unexpected type %T", x)
	}
	return nil
}

func _RequestResolutionUpdate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RequestResolutionUpdate)
	switch tag {
	case 4: // Result.placeOrderResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlaceOrderResult)
		err := b.DecodeMessage(msg)
		m.Result = &RequestResolutionUpdate_PlaceOrderResult{msg}
		return true, err
	case 5: // Result.cancelOrderResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancelOrderResult)
		err := b.DecodeMessage(msg)
		m.Result = &RequestResolutionUpdate_CancelOrderResult{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RequestResolutionUpdate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RequestResolutionUpdate)
	// Result
	switch x := m.Result.(type) {
	case *RequestResolutionUpdate_PlaceOrderResult:
		s := proto.Size(x.PlaceOrderResult)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestResolutionUpdate_CancelOrderResult:
		s := proto.Size(x.CancelOrderResult)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AnonymousSessionStatusUpdate struct {
	Expiration           int64    `protobuf:"varint,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnonymousSessionStatusUpdate) Reset()         { *m = AnonymousSessionStatusUpdate{} }
func (m *AnonymousSessionStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*AnonymousSessionStatusUpdate) ProtoMessage()    {}
func (*AnonymousSessionStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{14}
}

func (m *AnonymousSessionStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnonymousSessionStatusUpdate.Unmarshal(m, b)
}
func (m *AnonymousSessionStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnonymousSessionStatusUpdate.Marshal(b, m, deterministic)
}
func (m *AnonymousSessionStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnonymousSessionStatusUpdate.Merge(m, src)
}
func (m *AnonymousSessionStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_AnonymousSessionStatusUpdate.Size(m)
}
func (m *AnonymousSessionStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AnonymousSessionStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AnonymousSessionStatusUpdate proto.InternalMessageInfo

func (m *AnonymousSessionStatusUpdate) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *AnonymousSessionStatusUpdate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SessionStatusUpdate struct {
	Initialized bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	// Syncing means poller is running
	Syncing bool `protobuf:"varint,2,opt,name=syncing,proto3" json:"syncing,omitempty"`
	// Last sync is last time poller finished running
	LastSyncTime int64 `protobuf:"varint,3,opt,name=lastSyncTime,proto3" json:"lastSyncTime,omitempty"`
	// Expose error from poller
	SyncError            int32    `protobuf:"varint,4,opt,name=syncError,proto3" json:"syncError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStatusUpdate) Reset()         { *m = SessionStatusUpdate{} }
func (m *SessionStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*SessionStatusUpdate) ProtoMessage()    {}
func (*SessionStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{15}
}

func (m *SessionStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStatusUpdate.Unmarshal(m, b)
}
func (m *SessionStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStatusUpdate.Marshal(b, m, deterministic)
}
func (m *SessionStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStatusUpdate.Merge(m, src)
}
func (m *SessionStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_SessionStatusUpdate.Size(m)
}
func (m *SessionStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStatusUpdate proto.InternalMessageInfo

func (m *SessionStatusUpdate) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *SessionStatusUpdate) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

func (m *SessionStatusUpdate) GetLastSyncTime() int64 {
	if m != nil {
		return m.LastSyncTime
	}
	return 0
}

func (m *SessionStatusUpdate) GetSyncError() int32 {
	if m != nil {
		return m.SyncError
	}
	return 0
}

type PermissionsUpdate struct {
	OrderTypes           []PrivateOrder_Type               `protobuf:"varint,1,rep,name=orderTypes,proto3,enum=ProtobufBroker.PrivateOrder_Type" json:"orderTypes,omitempty"`
	FundingTypes         []FundingType                     `protobuf:"varint,2,rep,name=fundingTypes,proto3,enum=ProtobufBroker.FundingType" json:"fundingTypes,omitempty"`
	Agreements           []*PermissionsUpdate_Agreement    `protobuf:"bytes,4,rep,name=agreements,proto3" json:"agreements,omitempty"`
	CurrencyPairAllowed  bool                              `protobuf:"varint,5,opt,name=currencyPairAllowed,proto3" json:"currencyPairAllowed,omitempty"`
	LeverageLevels       *PermissionsUpdate_LeverageLevels `protobuf:"bytes,6,opt,name=leverageLevels,proto3" json:"leverageLevels,omitempty"`
	SupportsOrderExpiry  bool                              `protobuf:"varint,7,opt,name=supportsOrderExpiry,proto3" json:"supportsOrderExpiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PermissionsUpdate) Reset()         { *m = PermissionsUpdate{} }
func (m *PermissionsUpdate) String() string { return proto.CompactTextString(m) }
func (*PermissionsUpdate) ProtoMessage()    {}
func (*PermissionsUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{16}
}

func (m *PermissionsUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsUpdate.Unmarshal(m, b)
}
func (m *PermissionsUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsUpdate.Marshal(b, m, deterministic)
}
func (m *PermissionsUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsUpdate.Merge(m, src)
}
func (m *PermissionsUpdate) XXX_Size() int {
	return xxx_messageInfo_PermissionsUpdate.Size(m)
}
func (m *PermissionsUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsUpdate proto.InternalMessageInfo

func (m *PermissionsUpdate) GetOrderTypes() []PrivateOrder_Type {
	if m != nil {
		return m.OrderTypes
	}
	return nil
}

func (m *PermissionsUpdate) GetFundingTypes() []FundingType {
	if m != nil {
		return m.FundingTypes
	}
	return nil
}

func (m *PermissionsUpdate) GetAgreements() []*PermissionsUpdate_Agreement {
	if m != nil {
		return m.Agreements
	}
	return nil
}

func (m *PermissionsUpdate) GetCurrencyPairAllowed() bool {
	if m != nil {
		return m.CurrencyPairAllowed
	}
	return false
}

func (m *PermissionsUpdate) GetLeverageLevels() *PermissionsUpdate_LeverageLevels {
	if m != nil {
		return m.LeverageLevels
	}
	return nil
}

func (m *PermissionsUpdate) GetSupportsOrderExpiry() bool {
	if m != nil {
		return m.SupportsOrderExpiry
	}
	return false
}

type PermissionsUpdate_Agreement struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionsUpdate_Agreement) Reset()         { *m = PermissionsUpdate_Agreement{} }
func (m *PermissionsUpdate_Agreement) String() string { return proto.CompactTextString(m) }
func (*PermissionsUpdate_Agreement) ProtoMessage()    {}
func (*PermissionsUpdate_Agreement) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{16, 0}
}

func (m *PermissionsUpdate_Agreement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsUpdate_Agreement.Unmarshal(m, b)
}
func (m *PermissionsUpdate_Agreement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsUpdate_Agreement.Marshal(b, m, deterministic)
}
func (m *PermissionsUpdate_Agreement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsUpdate_Agreement.Merge(m, src)
}
func (m *PermissionsUpdate_Agreement) XXX_Size() int {
	return xxx_messageInfo_PermissionsUpdate_Agreement.Size(m)
}
func (m *PermissionsUpdate_Agreement) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsUpdate_Agreement.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsUpdate_Agreement proto.InternalMessageInfo

func (m *PermissionsUpdate_Agreement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PermissionsUpdate_Agreement) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type PermissionsUpdate_LeverageLevels struct {
	Buy                  []string `protobuf:"bytes,1,rep,name=buy,proto3" json:"buy,omitempty"`
	Sell                 []string `protobuf:"bytes,2,rep,name=sell,proto3" json:"sell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionsUpdate_LeverageLevels) Reset()         { *m = PermissionsUpdate_LeverageLevels{} }
func (m *PermissionsUpdate_LeverageLevels) String() string { return proto.CompactTextString(m) }
func (*PermissionsUpdate_LeverageLevels) ProtoMessage()    {}
func (*PermissionsUpdate_LeverageLevels) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{16, 1}
}

func (m *PermissionsUpdate_LeverageLevels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsUpdate_LeverageLevels.Unmarshal(m, b)
}
func (m *PermissionsUpdate_LeverageLevels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsUpdate_LeverageLevels.Marshal(b, m, deterministic)
}
func (m *PermissionsUpdate_LeverageLevels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsUpdate_LeverageLevels.Merge(m, src)
}
func (m *PermissionsUpdate_LeverageLevels) XXX_Size() int {
	return xxx_messageInfo_PermissionsUpdate_LeverageLevels.Size(m)
}
func (m *PermissionsUpdate_LeverageLevels) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsUpdate_LeverageLevels.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsUpdate_LeverageLevels proto.InternalMessageInfo

func (m *PermissionsUpdate_LeverageLevels) GetBuy() []string {
	if m != nil {
		return m.Buy
	}
	return nil
}

func (m *PermissionsUpdate_LeverageLevels) GetSell() []string {
	if m != nil {
		return m.Sell
	}
	return nil
}

type APIAccessorStatusUpdate struct {
	HasAccess            bool     `protobuf:"varint,1,opt,name=hasAccess,proto3" json:"hasAccess,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusString         string   `protobuf:"bytes,3,opt,name=statusString,proto3" json:"statusString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIAccessorStatusUpdate) Reset()         { *m = APIAccessorStatusUpdate{} }
func (m *APIAccessorStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*APIAccessorStatusUpdate) ProtoMessage()    {}
func (*APIAccessorStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{17}
}

func (m *APIAccessorStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIAccessorStatusUpdate.Unmarshal(m, b)
}
func (m *APIAccessorStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIAccessorStatusUpdate.Marshal(b, m, deterministic)
}
func (m *APIAccessorStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIAccessorStatusUpdate.Merge(m, src)
}
func (m *APIAccessorStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_APIAccessorStatusUpdate.Size(m)
}
func (m *APIAccessorStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_APIAccessorStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_APIAccessorStatusUpdate proto.InternalMessageInfo

func (m *APIAccessorStatusUpdate) GetHasAccess() bool {
	if m != nil {
		return m.HasAccess
	}
	return false
}

func (m *APIAccessorStatusUpdate) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *APIAccessorStatusUpdate) GetStatusString() string {
	if m != nil {
		return m.StatusString
	}
	return ""
}

type BrokerUpdateMessage struct {
	MarketId int64 `protobuf:"varint,11,opt,name=marketId,proto3" json:"marketId,omitempty"`
	// Types that are valid to be assigned to Update:
	//	*BrokerUpdateMessage_OrdersUpdate
	//	*BrokerUpdateMessage_TradesUpdate
	//	*BrokerUpdateMessage_BalancesUpdate
	//	*BrokerUpdateMessage_PositionsUpdate
	//	*BrokerUpdateMessage_RequestResolutionUpdate
	//	*BrokerUpdateMessage_AnonymousSessionStatusUpdate
	//	*BrokerUpdateMessage_PermissionsUpdate
	//	*BrokerUpdateMessage_SessionStatusUpdate
	//	*BrokerUpdateMessage_ApiAccessorStatusUpdate
	//	*BrokerUpdateMessage_AuthenticationResult
	Update               isBrokerUpdateMessage_Update `protobuf_oneof:"Update"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BrokerUpdateMessage) Reset()         { *m = BrokerUpdateMessage{} }
func (m *BrokerUpdateMessage) String() string { return proto.CompactTextString(m) }
func (*BrokerUpdateMessage) ProtoMessage()    {}
func (*BrokerUpdateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a300fef54c4624, []int{18}
}

func (m *BrokerUpdateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerUpdateMessage.Unmarshal(m, b)
}
func (m *BrokerUpdateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerUpdateMessage.Marshal(b, m, deterministic)
}
func (m *BrokerUpdateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerUpdateMessage.Merge(m, src)
}
func (m *BrokerUpdateMessage) XXX_Size() int {
	return xxx_messageInfo_BrokerUpdateMessage.Size(m)
}
func (m *BrokerUpdateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerUpdateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerUpdateMessage proto.InternalMessageInfo

func (m *BrokerUpdateMessage) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

type isBrokerUpdateMessage_Update interface {
	isBrokerUpdateMessage_Update()
}

type BrokerUpdateMessage_OrdersUpdate struct {
	OrdersUpdate *OrdersUpdate `protobuf:"bytes,1,opt,name=ordersUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_TradesUpdate struct {
	TradesUpdate *TradesUpdate `protobuf:"bytes,2,opt,name=tradesUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_BalancesUpdate struct {
	BalancesUpdate *BalancesUpdate `protobuf:"bytes,3,opt,name=balancesUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_PositionsUpdate struct {
	PositionsUpdate *PositionsUpdate `protobuf:"bytes,8,opt,name=positionsUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_RequestResolutionUpdate struct {
	RequestResolutionUpdate *RequestResolutionUpdate `protobuf:"bytes,4,opt,name=requestResolutionUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_AnonymousSessionStatusUpdate struct {
	AnonymousSessionStatusUpdate *AnonymousSessionStatusUpdate `protobuf:"bytes,5,opt,name=anonymousSessionStatusUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_PermissionsUpdate struct {
	PermissionsUpdate *PermissionsUpdate `protobuf:"bytes,6,opt,name=permissionsUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_SessionStatusUpdate struct {
	SessionStatusUpdate *SessionStatusUpdate `protobuf:"bytes,7,opt,name=sessionStatusUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_ApiAccessorStatusUpdate struct {
	ApiAccessorStatusUpdate *APIAccessorStatusUpdate `protobuf:"bytes,9,opt,name=apiAccessorStatusUpdate,proto3,oneof"`
}

type BrokerUpdateMessage_AuthenticationResult struct {
	AuthenticationResult *stream.AuthenticationResult `protobuf:"bytes,10,opt,name=authenticationResult,proto3,oneof"`
}

func (*BrokerUpdateMessage_OrdersUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_TradesUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_BalancesUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_PositionsUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_RequestResolutionUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_AnonymousSessionStatusUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_PermissionsUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_SessionStatusUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_ApiAccessorStatusUpdate) isBrokerUpdateMessage_Update() {}

func (*BrokerUpdateMessage_AuthenticationResult) isBrokerUpdateMessage_Update() {}

func (m *BrokerUpdateMessage) GetUpdate() isBrokerUpdateMessage_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *BrokerUpdateMessage) GetOrdersUpdate() *OrdersUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_OrdersUpdate); ok {
		return x.OrdersUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetTradesUpdate() *TradesUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_TradesUpdate); ok {
		return x.TradesUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetBalancesUpdate() *BalancesUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_BalancesUpdate); ok {
		return x.BalancesUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetPositionsUpdate() *PositionsUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_PositionsUpdate); ok {
		return x.PositionsUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetRequestResolutionUpdate() *RequestResolutionUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_RequestResolutionUpdate); ok {
		return x.RequestResolutionUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetAnonymousSessionStatusUpdate() *AnonymousSessionStatusUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_AnonymousSessionStatusUpdate); ok {
		return x.AnonymousSessionStatusUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetPermissionsUpdate() *PermissionsUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_PermissionsUpdate); ok {
		return x.PermissionsUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetSessionStatusUpdate() *SessionStatusUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_SessionStatusUpdate); ok {
		return x.SessionStatusUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetApiAccessorStatusUpdate() *APIAccessorStatusUpdate {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_ApiAccessorStatusUpdate); ok {
		return x.ApiAccessorStatusUpdate
	}
	return nil
}

func (m *BrokerUpdateMessage) GetAuthenticationResult() *stream.AuthenticationResult {
	if x, ok := m.GetUpdate().(*BrokerUpdateMessage_AuthenticationResult); ok {
		return x.AuthenticationResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BrokerUpdateMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BrokerUpdateMessage_OneofMarshaler, _BrokerUpdateMessage_OneofUnmarshaler, _BrokerUpdateMessage_OneofSizer, []interface{}{
		(*BrokerUpdateMessage_OrdersUpdate)(nil),
		(*BrokerUpdateMessage_TradesUpdate)(nil),
		(*BrokerUpdateMessage_BalancesUpdate)(nil),
		(*BrokerUpdateMessage_PositionsUpdate)(nil),
		(*BrokerUpdateMessage_RequestResolutionUpdate)(nil),
		(*BrokerUpdateMessage_AnonymousSessionStatusUpdate)(nil),
		(*BrokerUpdateMessage_PermissionsUpdate)(nil),
		(*BrokerUpdateMessage_SessionStatusUpdate)(nil),
		(*BrokerUpdateMessage_ApiAccessorStatusUpdate)(nil),
		(*BrokerUpdateMessage_AuthenticationResult)(nil),
	}
}

func _BrokerUpdateMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BrokerUpdateMessage)
	// Update
	switch x := m.Update.(type) {
	case *BrokerUpdateMessage_OrdersUpdate:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrdersUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_TradesUpdate:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TradesUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_BalancesUpdate:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BalancesUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_PositionsUpdate:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PositionsUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_RequestResolutionUpdate:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequestResolutionUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_AnonymousSessionStatusUpdate:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AnonymousSessionStatusUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_PermissionsUpdate:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PermissionsUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_SessionStatusUpdate:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SessionStatusUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_ApiAccessorStatusUpdate:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ApiAccessorStatusUpdate); err != nil {
			return err
		}
	case *BrokerUpdateMessage_AuthenticationResult:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthenticationResult); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BrokerUpdateMessage.Update has unexpected type %T", x)
	}
	return nil
}

func _BrokerUpdateMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BrokerUpdateMessage)
	switch tag {
	case 1: // Update.ordersUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrdersUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_OrdersUpdate{msg}
		return true, err
	case 2: // Update.tradesUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TradesUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_TradesUpdate{msg}
		return true, err
	case 3: // Update.balancesUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BalancesUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_BalancesUpdate{msg}
		return true, err
	case 8: // Update.positionsUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PositionsUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_PositionsUpdate{msg}
		return true, err
	case 4: // Update.requestResolutionUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestResolutionUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_RequestResolutionUpdate{msg}
		return true, err
	case 5: // Update.anonymousSessionStatusUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AnonymousSessionStatusUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_AnonymousSessionStatusUpdate{msg}
		return true, err
	case 6: // Update.permissionsUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PermissionsUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_PermissionsUpdate{msg}
		return true, err
	case 7: // Update.sessionStatusUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SessionStatusUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_SessionStatusUpdate{msg}
		return true, err
	case 9: // Update.apiAccessorStatusUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(APIAccessorStatusUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_ApiAccessorStatusUpdate{msg}
		return true, err
	case 10: // Update.authenticationResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(stream.AuthenticationResult)
		err := b.DecodeMessage(msg)
		m.Update = &BrokerUpdateMessage_AuthenticationResult{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BrokerUpdateMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BrokerUpdateMessage)
	// Update
	switch x := m.Update.(type) {
	case *BrokerUpdateMessage_OrdersUpdate:
		s := proto.Size(x.OrdersUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_TradesUpdate:
		s := proto.Size(x.TradesUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_BalancesUpdate:
		s := proto.Size(x.BalancesUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_PositionsUpdate:
		s := proto.Size(x.PositionsUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_RequestResolutionUpdate:
		s := proto.Size(x.RequestResolutionUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_AnonymousSessionStatusUpdate:
		s := proto.Size(x.AnonymousSessionStatusUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_PermissionsUpdate:
		s := proto.Size(x.PermissionsUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_SessionStatusUpdate:
		s := proto.Size(x.SessionStatusUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_ApiAccessorStatusUpdate:
		s := proto.Size(x.ApiAccessorStatusUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BrokerUpdateMessage_AuthenticationResult:
		s := proto.Size(x.AuthenticationResult)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*BrokerSessionMessage)(nil), "ProtobufBroker.BrokerSessionMessage")
	proto.RegisterType((*BrokerSessionMessage_Session)(nil), "ProtobufBroker.BrokerSessionMessage.Session")
	proto.RegisterType((*BrokerSessionMessage_AnonymousTradingSession)(nil), "ProtobufBroker.BrokerSessionMessage.AnonymousTradingSession")
	proto.RegisterType((*PlaceOrderRequest)(nil), "ProtobufBroker.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResult)(nil), "ProtobufBroker.PlaceOrderResult")
	proto.RegisterType((*CancelOrderRequest)(nil), "ProtobufBroker.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResult)(nil), "ProtobufBroker.CancelOrderResult")
	proto.RegisterType((*ReplaceOrderRequest)(nil), "ProtobufBroker.ReplaceOrderRequest")
	proto.RegisterType((*ClosePositionRequest)(nil), "ProtobufBroker.ClosePositionRequest")
	proto.RegisterType((*SyncRequest)(nil), "ProtobufBroker.SyncRequest")
	proto.RegisterType((*BrokerRequest)(nil), "ProtobufBroker.BrokerRequest")
	proto.RegisterType((*OrdersUpdate)(nil), "ProtobufBroker.OrdersUpdate")
	proto.RegisterType((*TradesUpdate)(nil), "ProtobufBroker.TradesUpdate")
	proto.RegisterType((*PositionsUpdate)(nil), "ProtobufBroker.PositionsUpdate")
	proto.RegisterType((*BalancesUpdate)(nil), "ProtobufBroker.BalancesUpdate")
	proto.RegisterType((*RequestResolutionUpdate)(nil), "ProtobufBroker.RequestResolutionUpdate")
	proto.RegisterType((*AnonymousSessionStatusUpdate)(nil), "ProtobufBroker.AnonymousSessionStatusUpdate")
	proto.RegisterType((*SessionStatusUpdate)(nil), "ProtobufBroker.SessionStatusUpdate")
	proto.RegisterType((*PermissionsUpdate)(nil), "ProtobufBroker.PermissionsUpdate")
	proto.RegisterType((*PermissionsUpdate_Agreement)(nil), "ProtobufBroker.PermissionsUpdate.Agreement")
	proto.RegisterType((*PermissionsUpdate_LeverageLevels)(nil), "ProtobufBroker.PermissionsUpdate.LeverageLevels")
	proto.RegisterType((*APIAccessorStatusUpdate)(nil), "ProtobufBroker.APIAccessorStatusUpdate")
	proto.RegisterType((*BrokerUpdateMessage)(nil), "ProtobufBroker.BrokerUpdateMessage")
}

func init() { proto.RegisterFile("broker/broker.proto", fileDescriptor_09a300fef54c4624) }

var fileDescriptor_09a300fef54c4624 = []byte{
	// 1285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0x77, 0x92, 0xb6, 0x49, 0x4e, 0xba, 0xd9, 0x76, 0x12, 0xfd, 0x6b, 0xe5, 0x5f, 0x2d, 0x5d,
	0x83, 0xc4, 0x4a, 0x40, 0x76, 0x59, 0xd0, 0x5e, 0xf1, 0x95, 0x94, 0x5d, 0x79, 0xb5, 0x0b, 0x84,
	0x69, 0x60, 0x11, 0x57, 0x4c, 0x9c, 0x69, 0x6a, 0xd5, 0xb1, 0xcd, 0x8c, 0x5d, 0x1a, 0x1e, 0x00,
	0x89, 0x6b, 0xc4, 0x3d, 0x6f, 0xc3, 0x83, 0x20, 0xde, 0x03, 0xcd, 0x87, 0x13, 0x7f, 0x4c, 0xda,
	0x85, 0x2b, 0xfb, 0x8c, 0xcf, 0xef, 0x37, 0x67, 0xce, 0x9c, 0x2f, 0x43, 0x6f, 0xc6, 0xa2, 0x4b,
	0xca, 0x1e, 0xaa, 0xc7, 0x30, 0x66, 0x51, 0x12, 0xa1, 0xee, 0x44, 0x3c, 0x66, 0xe9, 0xf9, 0x58,
	0xae, 0x0e, 0xfa, 0x5a, 0x29, 0x66, 0xfe, 0x15, 0x49, 0xa8, 0xd2, 0x1a, 0xf4, 0x78, 0xc2, 0x28,
	0x59, 0x3e, 0x54, 0x0f, 0xb5, 0xe8, 0xfc, 0xd5, 0x80, 0xbe, 0x42, 0x9d, 0x51, 0xce, 0xfd, 0x28,
	0xfc, 0x82, 0x72, 0x4e, 0x16, 0x14, 0xb9, 0xd0, 0xe4, 0x6a, 0xc5, 0xae, 0x9d, 0xd4, 0x1e, 0x74,
	0x1e, 0xbf, 0x3b, 0x2c, 0xee, 0x32, 0x34, 0xc1, 0x86, 0x5a, 0x74, 0x2d, 0x9c, 0xc1, 0xd1, 0x35,
	0x1c, 0x91, 0x30, 0x0a, 0x57, 0xcb, 0x28, 0xe5, 0x53, 0x46, 0xe6, 0x7e, 0xb8, 0xd0, 0x5a, 0x76,
	0x5d, 0x32, 0x7f, 0xf4, 0x5a, 0xcc, 0x23, 0x33, 0x87, 0x6b, 0xe1, 0x6d, 0xf4, 0x68, 0x00, 0xad,
	0x25, 0x61, 0x97, 0x34, 0x79, 0x3e, 0xb7, 0x1b, 0x27, 0xb5, 0x07, 0x0d, 0xbc, 0x96, 0x07, 0x4b,
	0x68, 0x66, 0x6a, 0xff, 0x83, 0xbd, 0x94, 0x53, 0xf6, 0x7c, 0x2e, 0x4f, 0xda, 0xc6, 0x5a, 0x42,
	0x36, 0x34, 0xe9, 0x75, 0xec, 0x33, 0xca, 0xa5, 0xa1, 0x0d, 0x9c, 0x89, 0xa8, 0x0f, 0xbb, 0x49,
	0x74, 0x49, 0x43, 0xc9, 0xda, 0xc6, 0x4a, 0x90, 0xdb, 0x9d, 0x93, 0xa9, 0xfc, 0xb0, 0x23, 0x3f,
	0xac, 0xe5, 0xc1, 0x25, 0x1c, 0x8d, 0xb6, 0x5b, 0x49, 0xaf, 0xbd, 0x0b, 0x12, 0x2e, 0xa8, 0x36,
	0x60, 0x2d, 0x6f, 0x36, 0xaa, 0xe7, 0x37, 0xba, 0x07, 0x20, 0x2d, 0x21, 0x89, 0x70, 0xa2, 0x3a,
	0x59, 0x6e, 0x65, 0x7c, 0x17, 0xee, 0x68, 0xf2, 0xd3, 0x28, 0x3c, 0xf7, 0x17, 0xce, 0xaf, 0x35,
	0x38, 0x9c, 0x04, 0xc4, 0xa3, 0x5f, 0xb1, 0x39, 0x65, 0x98, 0xfe, 0x98, 0x52, 0x9e, 0xa0, 0xc7,
	0xb0, 0x1b, 0x09, 0x59, 0x5f, 0xc3, 0x71, 0xf9, 0x1a, 0x26, 0x2a, 0x7c, 0x14, 0x46, 0xa9, 0xa2,
	0xcf, 0x60, 0xdf, 0x0b, 0x22, 0xee, 0x87, 0x0b, 0xb9, 0x2c, 0x37, 0xbf, 0x0d, 0x5a, 0x40, 0x38,
	0x3f, 0xc0, 0x41, 0xde, 0x14, 0x9e, 0x06, 0xff, 0xcd, 0x12, 0x1b, 0x9a, 0xf2, 0x65, 0x7d, 0x6d,
	0x99, 0xe8, 0x0c, 0x01, 0x9d, 0x92, 0xd0, 0xa3, 0x41, 0xe1, 0xb4, 0x39, 0xfd, 0x7a, 0x51, 0xff,
	0x3d, 0x38, 0x2c, 0xe8, 0x4b, 0x93, 0xb6, 0xd3, 0xff, 0x59, 0x83, 0x1e, 0xa6, 0x71, 0xc5, 0x9d,
	0x5b, 0x11, 0xe8, 0x13, 0xe8, 0x30, 0x05, 0x58, 0xd2, 0x30, 0x79, 0xad, 0x43, 0xe6, 0x01, 0xe8,
	0x5b, 0x38, 0xca, 0x89, 0xa7, 0xff, 0xd6, 0xff, 0xdb, 0xc0, 0xce, 0x13, 0xe8, 0x0b, 0x99, 0x4e,
	0x22, 0xee, 0x8b, 0xc0, 0xc9, 0x4e, 0x72, 0x0f, 0x20, 0xd6, 0x4b, 0x6b, 0x6f, 0xe5, 0x56, 0x9c,
	0x3b, 0xd0, 0x39, 0x5b, 0x85, 0x9e, 0x56, 0x77, 0xfe, 0x6e, 0xc0, 0x1d, 0xb5, 0x6f, 0x46, 0xd0,
	0x85, 0xba, 0x9f, 0x79, 0xa1, 0xee, 0xcf, 0x0b, 0x89, 0xd8, 0x2c, 0x26, 0x22, 0xfa, 0x1a, 0x0e,
	0x2b, 0xbe, 0xd4, 0x2e, 0xba, 0x5f, 0x39, 0x56, 0x59, 0xd1, 0xb5, 0x70, 0x15, 0x8d, 0xa6, 0x80,
	0xbc, 0x4a, 0x00, 0x68, 0x57, 0x39, 0x65, 0xce, 0x6a, 0xa8, 0xb8, 0x16, 0x36, 0xe0, 0xd1, 0x2b,
	0xe8, 0xb1, 0xea, 0xb5, 0xdb, 0x7b, 0x92, 0xf6, 0xcd, 0x32, 0xad, 0x21, 0x42, 0x5c, 0x0b, 0x9b,
	0x18, 0xd0, 0xa7, 0xd0, 0xe1, 0x1b, 0x77, 0xca, 0xd2, 0xd1, 0x79, 0xfc, 0xff, 0x32, 0x61, 0xce,
	0xe3, 0xae, 0x85, 0xf3, 0x08, 0xf4, 0x3d, 0xf4, 0x3d, 0xc3, 0x3d, 0xda, 0xbb, 0x92, 0xe9, 0xad,
	0xca, 0x89, 0x0d, 0xba, 0xae, 0x85, 0x8d, 0x1c, 0xe3, 0x36, 0x34, 0xb3, 0x7b, 0xfe, 0x1c, 0xf6,
	0xa5, 0xdd, 0xfc, 0x9b, 0x78, 0x4e, 0x12, 0x8a, 0x3e, 0x84, 0x3d, 0x19, 0xe1, 0xdc, 0xae, 0x9d,
	0x34, 0x6e, 0x8d, 0x42, 0xad, 0x2b, 0x58, 0x44, 0x01, 0xa4, 0x39, 0x96, 0x44, 0xca, 0xb7, 0xb0,
	0x48, 0x10, 0xd6, 0xba, 0xce, 0x04, 0xee, 0x66, 0x96, 0x66, 0x44, 0x1f, 0x43, 0x3b, 0x8b, 0xd1,
	0x8c, 0xeb, 0x8d, 0x2d, 0x5c, 0xeb, 0x43, 0x6e, 0x10, 0xce, 0x33, 0xe8, 0x8e, 0x49, 0x20, 0xae,
	0x7d, 0x63, 0x59, 0x6b, 0xa6, 0x57, 0x34, 0x9f, 0x5d, 0xe9, 0x54, 0xfa, 0x3b, 0x5e, 0x6b, 0x3a,
	0xbf, 0xd4, 0xe1, 0x48, 0x7b, 0x0c, 0x53, 0x1e, 0x05, 0xa9, 0xa0, 0xd7, 0x8c, 0xe5, 0xbc, 0xe8,
	0xc3, 0x2e, 0x65, 0x2c, 0x52, 0x75, 0x6f, 0x17, 0x2b, 0x41, 0x14, 0x92, 0xa5, 0x6a, 0x7a, 0xba,
	0xbf, 0x64, 0x22, 0xfa, 0x12, 0x0e, 0xe2, 0x52, 0xed, 0xd4, 0xe1, 0x72, 0x72, 0x53, 0xaa, 0x08,
	0x3d, 0xd7, 0xc2, 0x15, 0xac, 0xc8, 0x3d, 0xaf, 0x5c, 0xf9, 0x74, 0xd4, 0xdc, 0xbf, 0x31, 0x4f,
	0x34, 0x63, 0x15, 0x3d, 0x6e, 0xc1, 0x9e, 0x7a, 0x73, 0xa6, 0x70, 0xbc, 0x6e, 0x79, 0xba, 0x1d,
	0x9d, 0x25, 0x24, 0x49, 0x33, 0xf7, 0x16, 0xbb, 0x58, 0xad, 0xdc, 0xc5, 0xcc, 0xbd, 0xcf, 0xf9,
	0xad, 0x06, 0x3d, 0x13, 0xdb, 0x09, 0x74, 0xfc, 0xd0, 0x4f, 0x7c, 0x12, 0xf8, 0x3f, 0x53, 0xe5,
	0xe3, 0x16, 0xce, 0x2f, 0x09, 0xb7, 0x8a, 0xa4, 0xf1, 0xc3, 0x85, 0x64, 0x6c, 0xe1, 0x4c, 0x44,
	0x0e, 0xec, 0x07, 0x84, 0x27, 0x22, 0xc3, 0xa6, 0xfe, 0x92, 0xea, 0x8e, 0x5a, 0x58, 0x43, 0xc7,
	0xd0, 0x16, 0xea, 0x4f, 0xe5, 0x75, 0xed, 0xc8, 0xeb, 0xda, 0x2c, 0x38, 0xbf, 0xef, 0xc0, 0xe1,
	0x84, 0xb2, 0xa5, 0x2f, 0x0d, 0xcb, 0x6c, 0x7a, 0x0a, 0x20, 0x83, 0x7e, 0xba, 0x8a, 0x75, 0x08,
	0x75, 0x0d, 0x35, 0x2d, 0x97, 0x24, 0x43, 0xa1, 0x39, 0xae, 0x1f, 0x58, 0x38, 0x07, 0x44, 0xa7,
	0xb0, 0x7f, 0x9e, 0x86, 0x62, 0x64, 0x50, 0x44, 0x75, 0x49, 0x54, 0x29, 0x10, 0xcf, 0x36, 0x3a,
	0x92, 0xa2, 0x00, 0x42, 0x2f, 0x00, 0xc8, 0x82, 0x51, 0xd9, 0x04, 0xb8, 0xbd, 0x23, 0xc3, 0xf9,
	0x9d, 0x8a, 0x2d, 0xe5, 0x23, 0x0c, 0x47, 0x19, 0x06, 0xe7, 0xe0, 0xe8, 0x11, 0xf4, 0xbc, 0x94,
	0x31, 0x1a, 0x7a, 0xab, 0x09, 0xf1, 0xd9, 0x28, 0x08, 0xa2, 0x9f, 0xe8, 0x5c, 0x46, 0x4e, 0x0b,
	0x9b, 0x3e, 0xa1, 0xef, 0xa0, 0x1b, 0xd0, 0x2b, 0xca, 0xc8, 0x82, 0xbe, 0xa4, 0x57, 0x34, 0xe0,
	0xba, 0x6e, 0x3e, 0xba, 0xdd, 0x84, 0x97, 0x05, 0x1c, 0x2e, 0xf1, 0x08, 0x5b, 0x78, 0x1a, 0xc7,
	0x11, 0x4b, 0xb8, 0xf4, 0xe1, 0x53, 0x11, 0x41, 0x2b, 0xd9, 0x66, 0x5a, 0xd8, 0xf4, 0x69, 0xf0,
	0x3e, 0xb4, 0xd7, 0xc7, 0x42, 0x07, 0xd0, 0xb8, 0xa4, 0x2b, 0x9d, 0x93, 0xe2, 0x15, 0x21, 0xd8,
	0x99, 0x45, 0xf3, 0x95, 0x0e, 0x3b, 0xf9, 0x3e, 0x78, 0x02, 0xdd, 0xa2, 0x19, 0x02, 0x37, 0x4b,
	0x57, 0xf2, 0x52, 0xdb, 0x58, 0xbc, 0x0a, 0x1c, 0xa7, 0x41, 0x20, 0xaf, 0xa7, 0x8d, 0xe5, 0xbb,
	0xc3, 0xe1, 0x68, 0x34, 0x79, 0x3e, 0xf2, 0x3c, 0xca, 0x79, 0xc4, 0x0a, 0x01, 0x7b, 0x0c, 0xed,
	0x0b, 0xc2, 0xd5, 0x27, 0x1d, 0xae, 0x9b, 0x05, 0x31, 0x93, 0x72, 0xa9, 0xad, 0x4b, 0x83, 0x96,
	0x44, 0xa8, 0xaa, 0xb7, 0xb3, 0x84, 0x89, 0x48, 0x56, 0x05, 0xa2, 0xb0, 0xe6, 0xfc, 0xd1, 0x84,
	0x9e, 0xf2, 0xa6, 0xda, 0x2a, 0x1b, 0xe9, 0xf3, 0x5d, 0xb8, 0x53, 0xea, 0xc2, 0x63, 0xd8, 0x8f,
	0x72, 0xb5, 0x5d, 0xcf, 0xfc, 0x95, 0x5a, 0x9c, 0xaf, 0xff, 0xae, 0x85, 0x0b, 0x18, 0xc1, 0x91,
	0xe4, 0x2a, 0xfb, 0xb6, 0x39, 0x27, 0x5f, 0xfd, 0x05, 0x47, 0x1e, 0x83, 0x5c, 0xe8, 0xce, 0x0a,
	0x55, 0x58, 0xb7, 0xed, 0x7b, 0xdb, 0x2a, 0xef, 0x9a, 0xa7, 0x84, 0x43, 0x2f, 0xe0, 0x6e, 0x5c,
	0xec, 0x10, 0x76, 0x4b, 0x52, 0x55, 0x9b, 0x42, 0x51, 0xcd, 0xb5, 0x70, 0x19, 0x89, 0x3c, 0x31,
	0x81, 0x19, 0x6b, 0xba, 0xae, 0xbf, 0x6f, 0x57, 0xfb, 0xbf, 0x51, 0x5d, 0xfc, 0xae, 0x6c, 0x61,
	0x42, 0x0c, 0x8e, 0xc9, 0x0d, 0x05, 0x53, 0x17, 0xe6, 0xca, 0x7f, 0xd8, 0x4d, 0x45, 0xd6, 0xb5,
	0xf0, 0x8d, 0x9c, 0x72, 0xfa, 0x2a, 0x67, 0x9c, 0x4e, 0xcd, 0xfb, 0xb7, 0xa6, 0xa6, 0x9c, 0xbe,
	0x2a, 0x55, 0xef, 0x15, 0xf4, 0xb8, 0xc1, 0xfa, 0xa6, 0x79, 0x4e, 0x32, 0x1b, 0x6d, 0x62, 0x10,
	0x97, 0x40, 0x62, 0xdf, 0x94, 0x4c, 0x76, 0xdb, 0x7c, 0x09, 0x5b, 0x72, 0x4f, 0xfe, 0x33, 0x9a,
	0x99, 0xc4, 0x2c, 0x45, 0xd2, 0xe4, 0x82, 0x86, 0x89, 0xef, 0x11, 0x35, 0x08, 0xc9, 0xae, 0x08,
	0xa5, 0x59, 0xea, 0x4c, 0xfd, 0x45, 0x8f, 0x0c, 0xba, 0x62, 0x96, 0x32, 0x71, 0x88, 0xde, 0xa8,
	0x76, 0x99, 0xed, 0xc9, 0xbf, 0xef, 0x0f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x72, 0xfd, 0x21,
	0x79, 0xcf, 0x0f, 0x00, 0x00,
}
