// Code generated by protoc-gen-go. DO NOT EDIT.
// source: markets/market.proto

package ProtobufMarkets

/*
Package ProtobufMarkets contains definitions for market update messages;
the main wrapper messages is a MarketUpdateMessage.
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Market represents a currency pair on a particular exchange.
type Market struct {
	// Prefer integer ids to string slugs (far fewer bytes)
	ExchangeId     uint64 `protobuf:"varint,3,opt,name=exchangeId" json:"exchangeId,omitempty"`
	CurrencyPairId uint64 `protobuf:"varint,4,opt,name=currencyPairId" json:"currencyPairId,omitempty"`
	// New IDs from SQL; TODO remove 1,2,3,4 when migrationt o 5,6 is complete
	MarketId uint64 `protobuf:"varint,5,opt,name=marketId" json:"marketId,omitempty"`
	// Deprecated
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	CurrencyPair         string   `protobuf:"bytes,2,opt,name=currencyPair" json:"currencyPair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{0}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (dst *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(dst, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetExchangeId() uint64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *Market) GetCurrencyPairId() uint64 {
	if m != nil {
		return m.CurrencyPairId
	}
	return 0
}

func (m *Market) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Market) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Market) GetCurrencyPair() string {
	if m != nil {
		return m.CurrencyPair
	}
	return ""
}

// Order represents an ask or a bid.
type Order struct {
	PriceStr  string `protobuf:"bytes,3,opt,name=priceStr" json:"priceStr,omitempty"`
	AmountStr string `protobuf:"bytes,4,opt,name=amountStr" json:"amountStr,omitempty"`
	// Deprecated
	Price                float32  `protobuf:"fixed32,1,opt,name=price" json:"price,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{1}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetPriceStr() string {
	if m != nil {
		return m.PriceStr
	}
	return ""
}

func (m *Order) GetAmountStr() string {
	if m != nil {
		return m.AmountStr
	}
	return ""
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// Trade is a single trade in TradesUpdate
type Trade struct {
	// Exchange-specific ID
	ExternalId      string `protobuf:"bytes,11,opt,name=externalId" json:"externalId,omitempty"`
	Timestamp       int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	TimestampMillis int64  `protobuf:"varint,5,opt,name=timestampMillis" json:"timestampMillis,omitempty"`
	TimestampNano   int64  `protobuf:"varint,10,opt,name=timestampNano" json:"timestampNano,omitempty"`
	PriceStr        string `protobuf:"bytes,8,opt,name=priceStr" json:"priceStr,omitempty"`
	AmountStr       string `protobuf:"bytes,9,opt,name=amountStr" json:"amountStr,omitempty"`
	// Deprecated
	Price                float32  `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount" json:"amount,omitempty"`
	PriceDouble          float64  `protobuf:"fixed64,6,opt,name=priceDouble" json:"priceDouble,omitempty"`
	AmountDouble         float64  `protobuf:"fixed64,7,opt,name=amountDouble" json:"amountDouble,omitempty"`
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{2}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (dst *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(dst, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Trade) GetTimestampMillis() int64 {
	if m != nil {
		return m.TimestampMillis
	}
	return 0
}

func (m *Trade) GetTimestampNano() int64 {
	if m != nil {
		return m.TimestampNano
	}
	return 0
}

func (m *Trade) GetPriceStr() string {
	if m != nil {
		return m.PriceStr
	}
	return ""
}

func (m *Trade) GetAmountStr() string {
	if m != nil {
		return m.AmountStr
	}
	return ""
}

func (m *Trade) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetPriceDouble() float64 {
	if m != nil {
		return m.PriceDouble
	}
	return 0
}

func (m *Trade) GetAmountDouble() float64 {
	if m != nil {
		return m.AmountDouble
	}
	return 0
}

func (m *Trade) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// MarketUpdateMessage is the primary message for market updates; it wraps all
// other more specific update types.
type MarketUpdateMessage struct {
	Market *Market `protobuf:"bytes,9,opt,name=market" json:"market,omitempty"`
	// Types that are valid to be assigned to Update:
	//	*MarketUpdateMessage_OrderBookUpdate
	//	*MarketUpdateMessage_OrderBookDeltaUpdate
	//	*MarketUpdateMessage_OrderBookSpreadUpdate
	//	*MarketUpdateMessage_TradesUpdate
	//	*MarketUpdateMessage_IntervalsUpdate
	//	*MarketUpdateMessage_SummaryUpdate
	//	*MarketUpdateMessage_SparklineUpdate
	Update               isMarketUpdateMessage_Update `protobuf_oneof:"Update"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MarketUpdateMessage) Reset()         { *m = MarketUpdateMessage{} }
func (m *MarketUpdateMessage) String() string { return proto.CompactTextString(m) }
func (*MarketUpdateMessage) ProtoMessage()    {}
func (*MarketUpdateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{3}
}
func (m *MarketUpdateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketUpdateMessage.Unmarshal(m, b)
}
func (m *MarketUpdateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketUpdateMessage.Marshal(b, m, deterministic)
}
func (dst *MarketUpdateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketUpdateMessage.Merge(dst, src)
}
func (m *MarketUpdateMessage) XXX_Size() int {
	return xxx_messageInfo_MarketUpdateMessage.Size(m)
}
func (m *MarketUpdateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketUpdateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MarketUpdateMessage proto.InternalMessageInfo

type isMarketUpdateMessage_Update interface {
	isMarketUpdateMessage_Update()
}

type MarketUpdateMessage_OrderBookUpdate struct {
	OrderBookUpdate *OrderBookUpdate `protobuf:"bytes,2,opt,name=orderBookUpdate,oneof"`
}
type MarketUpdateMessage_OrderBookDeltaUpdate struct {
	OrderBookDeltaUpdate *OrderBookDeltaUpdate `protobuf:"bytes,3,opt,name=orderBookDeltaUpdate,oneof"`
}
type MarketUpdateMessage_OrderBookSpreadUpdate struct {
	OrderBookSpreadUpdate *OrderBookSpreadUpdate `protobuf:"bytes,11,opt,name=orderBookSpreadUpdate,oneof"`
}
type MarketUpdateMessage_TradesUpdate struct {
	TradesUpdate *TradesUpdate `protobuf:"bytes,4,opt,name=tradesUpdate,oneof"`
}
type MarketUpdateMessage_IntervalsUpdate struct {
	IntervalsUpdate *IntervalsUpdate `protobuf:"bytes,5,opt,name=intervalsUpdate,oneof"`
}
type MarketUpdateMessage_SummaryUpdate struct {
	SummaryUpdate *SummaryUpdate `protobuf:"bytes,6,opt,name=summaryUpdate,oneof"`
}
type MarketUpdateMessage_SparklineUpdate struct {
	SparklineUpdate *SparklineUpdate `protobuf:"bytes,7,opt,name=sparklineUpdate,oneof"`
}

func (*MarketUpdateMessage_OrderBookUpdate) isMarketUpdateMessage_Update()       {}
func (*MarketUpdateMessage_OrderBookDeltaUpdate) isMarketUpdateMessage_Update()  {}
func (*MarketUpdateMessage_OrderBookSpreadUpdate) isMarketUpdateMessage_Update() {}
func (*MarketUpdateMessage_TradesUpdate) isMarketUpdateMessage_Update()          {}
func (*MarketUpdateMessage_IntervalsUpdate) isMarketUpdateMessage_Update()       {}
func (*MarketUpdateMessage_SummaryUpdate) isMarketUpdateMessage_Update()         {}
func (*MarketUpdateMessage_SparklineUpdate) isMarketUpdateMessage_Update()       {}

func (m *MarketUpdateMessage) GetUpdate() isMarketUpdateMessage_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *MarketUpdateMessage) GetMarket() *Market {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *MarketUpdateMessage) GetOrderBookUpdate() *OrderBookUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_OrderBookUpdate); ok {
		return x.OrderBookUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetOrderBookDeltaUpdate() *OrderBookDeltaUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_OrderBookDeltaUpdate); ok {
		return x.OrderBookDeltaUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetOrderBookSpreadUpdate() *OrderBookSpreadUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_OrderBookSpreadUpdate); ok {
		return x.OrderBookSpreadUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetTradesUpdate() *TradesUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_TradesUpdate); ok {
		return x.TradesUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetIntervalsUpdate() *IntervalsUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_IntervalsUpdate); ok {
		return x.IntervalsUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetSummaryUpdate() *SummaryUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_SummaryUpdate); ok {
		return x.SummaryUpdate
	}
	return nil
}

func (m *MarketUpdateMessage) GetSparklineUpdate() *SparklineUpdate {
	if x, ok := m.GetUpdate().(*MarketUpdateMessage_SparklineUpdate); ok {
		return x.SparklineUpdate
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MarketUpdateMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MarketUpdateMessage_OneofMarshaler, _MarketUpdateMessage_OneofUnmarshaler, _MarketUpdateMessage_OneofSizer, []interface{}{
		(*MarketUpdateMessage_OrderBookUpdate)(nil),
		(*MarketUpdateMessage_OrderBookDeltaUpdate)(nil),
		(*MarketUpdateMessage_OrderBookSpreadUpdate)(nil),
		(*MarketUpdateMessage_TradesUpdate)(nil),
		(*MarketUpdateMessage_IntervalsUpdate)(nil),
		(*MarketUpdateMessage_SummaryUpdate)(nil),
		(*MarketUpdateMessage_SparklineUpdate)(nil),
	}
}

func _MarketUpdateMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MarketUpdateMessage)
	// Update
	switch x := m.Update.(type) {
	case *MarketUpdateMessage_OrderBookUpdate:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderBookUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_OrderBookDeltaUpdate:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderBookDeltaUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_OrderBookSpreadUpdate:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderBookSpreadUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_TradesUpdate:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TradesUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_IntervalsUpdate:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IntervalsUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_SummaryUpdate:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SummaryUpdate); err != nil {
			return err
		}
	case *MarketUpdateMessage_SparklineUpdate:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SparklineUpdate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MarketUpdateMessage.Update has unexpected type %T", x)
	}
	return nil
}

func _MarketUpdateMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MarketUpdateMessage)
	switch tag {
	case 2: // Update.orderBookUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderBookUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_OrderBookUpdate{msg}
		return true, err
	case 3: // Update.orderBookDeltaUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderBookDeltaUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_OrderBookDeltaUpdate{msg}
		return true, err
	case 11: // Update.orderBookSpreadUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderBookSpreadUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_OrderBookSpreadUpdate{msg}
		return true, err
	case 4: // Update.tradesUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TradesUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_TradesUpdate{msg}
		return true, err
	case 5: // Update.intervalsUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntervalsUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_IntervalsUpdate{msg}
		return true, err
	case 6: // Update.summaryUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SummaryUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_SummaryUpdate{msg}
		return true, err
	case 7: // Update.sparklineUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SparklineUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &MarketUpdateMessage_SparklineUpdate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MarketUpdateMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MarketUpdateMessage)
	// Update
	switch x := m.Update.(type) {
	case *MarketUpdateMessage_OrderBookUpdate:
		s := proto.Size(x.OrderBookUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_OrderBookDeltaUpdate:
		s := proto.Size(x.OrderBookDeltaUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_OrderBookSpreadUpdate:
		s := proto.Size(x.OrderBookSpreadUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_TradesUpdate:
		s := proto.Size(x.TradesUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_IntervalsUpdate:
		s := proto.Size(x.IntervalsUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_SummaryUpdate:
		s := proto.Size(x.SummaryUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MarketUpdateMessage_SparklineUpdate:
		s := proto.Size(x.SparklineUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// OrderBookUpdate represents a snapshot of the order book: a set of asks and
// bids for the particular aggregation modulus.
type OrderBookUpdate struct {
	// Aggregation modulus is a value which all bids and asks in this particular
	// OrderBookUpdate are divisible by. E.g. could be 1 (no aggregation), 5, 10,
	// 50, 100, etc. Exact possible values are set for each market individually.
	AggregationModulusStr string   `protobuf:"bytes,4,opt,name=aggregationModulusStr" json:"aggregationModulusStr,omitempty"`
	SeqNum                int32    `protobuf:"varint,5,opt,name=seqNum" json:"seqNum,omitempty"`
	Bids                  []*Order `protobuf:"bytes,1,rep,name=bids" json:"bids,omitempty"`
	Asks                  []*Order `protobuf:"bytes,2,rep,name=asks" json:"asks,omitempty"`
	// Deprecated
	AggregationModulus   float32  `protobuf:"fixed32,3,opt,name=aggregationModulus" json:"aggregationModulus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookUpdate) Reset()         { *m = OrderBookUpdate{} }
func (m *OrderBookUpdate) String() string { return proto.CompactTextString(m) }
func (*OrderBookUpdate) ProtoMessage()    {}
func (*OrderBookUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{4}
}
func (m *OrderBookUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookUpdate.Unmarshal(m, b)
}
func (m *OrderBookUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookUpdate.Marshal(b, m, deterministic)
}
func (dst *OrderBookUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookUpdate.Merge(dst, src)
}
func (m *OrderBookUpdate) XXX_Size() int {
	return xxx_messageInfo_OrderBookUpdate.Size(m)
}
func (m *OrderBookUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookUpdate proto.InternalMessageInfo

func (m *OrderBookUpdate) GetAggregationModulusStr() string {
	if m != nil {
		return m.AggregationModulusStr
	}
	return ""
}

func (m *OrderBookUpdate) GetSeqNum() int32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *OrderBookUpdate) GetBids() []*Order {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBookUpdate) GetAsks() []*Order {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBookUpdate) GetAggregationModulus() float32 {
	if m != nil {
		return m.AggregationModulus
	}
	return 0
}

// OrderBookDeltaUpdate represents a delta which needs to be applied to the
// local order book.
type OrderBookDeltaUpdate struct {
	// Aggregation modulus is a value which all bids and asks in this particular
	// OrderBookUpdate are divisible by. E.g. could be 1 (no aggregation), 5, 10,
	// 50, 100, etc. Exact possible values are set for each market individually.
	AggregationModulus    float32 `protobuf:"fixed32,3,opt,name=aggregationModulus" json:"aggregationModulus,omitempty"`
	AggregationModulusStr string  `protobuf:"bytes,4,opt,name=aggregationModulusStr" json:"aggregationModulusStr,omitempty"`
	SeqNum                int32   `protobuf:"varint,5,opt,name=seqNum" json:"seqNum,omitempty"`
	// Deltas for bids
	Bids *OrderBookDeltaUpdate_OrderDeltas `protobuf:"bytes,1,opt,name=bids" json:"bids,omitempty"`
	// Deltas for asks
	Asks                 *OrderBookDeltaUpdate_OrderDeltas `protobuf:"bytes,2,opt,name=asks" json:"asks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *OrderBookDeltaUpdate) Reset()         { *m = OrderBookDeltaUpdate{} }
func (m *OrderBookDeltaUpdate) String() string { return proto.CompactTextString(m) }
func (*OrderBookDeltaUpdate) ProtoMessage()    {}
func (*OrderBookDeltaUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{5}
}
func (m *OrderBookDeltaUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookDeltaUpdate.Unmarshal(m, b)
}
func (m *OrderBookDeltaUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookDeltaUpdate.Marshal(b, m, deterministic)
}
func (dst *OrderBookDeltaUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookDeltaUpdate.Merge(dst, src)
}
func (m *OrderBookDeltaUpdate) XXX_Size() int {
	return xxx_messageInfo_OrderBookDeltaUpdate.Size(m)
}
func (m *OrderBookDeltaUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookDeltaUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookDeltaUpdate proto.InternalMessageInfo

func (m *OrderBookDeltaUpdate) GetAggregationModulus() float32 {
	if m != nil {
		return m.AggregationModulus
	}
	return 0
}

func (m *OrderBookDeltaUpdate) GetAggregationModulusStr() string {
	if m != nil {
		return m.AggregationModulusStr
	}
	return ""
}

func (m *OrderBookDeltaUpdate) GetSeqNum() int32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *OrderBookDeltaUpdate) GetBids() *OrderBookDeltaUpdate_OrderDeltas {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBookDeltaUpdate) GetAsks() *OrderBookDeltaUpdate_OrderDeltas {
	if m != nil {
		return m.Asks
	}
	return nil
}

type OrderBookDeltaUpdate_OrderDeltas struct {
	// Either add a new order at a particular price, or replace existing one
	// (with the new amount)
	Set []*Order `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
	// TODO: I see we don't really use deltas, and just use set?
	Delta []*Order `protobuf:"bytes,2,rep,name=delta" json:"delta,omitempty"`
	// Remove order at a particular price
	Remove               []float32 `protobuf:"fixed32,3,rep,name=remove" json:"remove,omitempty"`
	RemoveStr            []string  `protobuf:"bytes,4,rep,name=removeStr" json:"removeStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderBookDeltaUpdate_OrderDeltas) Reset()         { *m = OrderBookDeltaUpdate_OrderDeltas{} }
func (m *OrderBookDeltaUpdate_OrderDeltas) String() string { return proto.CompactTextString(m) }
func (*OrderBookDeltaUpdate_OrderDeltas) ProtoMessage()    {}
func (*OrderBookDeltaUpdate_OrderDeltas) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{5, 0}
}
func (m *OrderBookDeltaUpdate_OrderDeltas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas.Unmarshal(m, b)
}
func (m *OrderBookDeltaUpdate_OrderDeltas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas.Marshal(b, m, deterministic)
}
func (dst *OrderBookDeltaUpdate_OrderDeltas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas.Merge(dst, src)
}
func (m *OrderBookDeltaUpdate_OrderDeltas) XXX_Size() int {
	return xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas.Size(m)
}
func (m *OrderBookDeltaUpdate_OrderDeltas) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookDeltaUpdate_OrderDeltas proto.InternalMessageInfo

func (m *OrderBookDeltaUpdate_OrderDeltas) GetSet() []*Order {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *OrderBookDeltaUpdate_OrderDeltas) GetDelta() []*Order {
	if m != nil {
		return m.Delta
	}
	return nil
}

func (m *OrderBookDeltaUpdate_OrderDeltas) GetRemove() []float32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (m *OrderBookDeltaUpdate_OrderDeltas) GetRemoveStr() []string {
	if m != nil {
		return m.RemoveStr
	}
	return nil
}

// OrderBookSpreadUpdate represents only the best bid & ask
type OrderBookSpreadUpdate struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Bid                  *Order   `protobuf:"bytes,2,opt,name=bid" json:"bid,omitempty"`
	Ask                  *Order   `protobuf:"bytes,3,opt,name=ask" json:"ask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookSpreadUpdate) Reset()         { *m = OrderBookSpreadUpdate{} }
func (m *OrderBookSpreadUpdate) String() string { return proto.CompactTextString(m) }
func (*OrderBookSpreadUpdate) ProtoMessage()    {}
func (*OrderBookSpreadUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{6}
}
func (m *OrderBookSpreadUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookSpreadUpdate.Unmarshal(m, b)
}
func (m *OrderBookSpreadUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookSpreadUpdate.Marshal(b, m, deterministic)
}
func (dst *OrderBookSpreadUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookSpreadUpdate.Merge(dst, src)
}
func (m *OrderBookSpreadUpdate) XXX_Size() int {
	return xxx_messageInfo_OrderBookSpreadUpdate.Size(m)
}
func (m *OrderBookSpreadUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookSpreadUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookSpreadUpdate proto.InternalMessageInfo

func (m *OrderBookSpreadUpdate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OrderBookSpreadUpdate) GetBid() *Order {
	if m != nil {
		return m.Bid
	}
	return nil
}

func (m *OrderBookSpreadUpdate) GetAsk() *Order {
	if m != nil {
		return m.Ask
	}
	return nil
}

// TradesUpdate represents a set of new trades.
type TradesUpdate struct {
	Trades               []*Trade `protobuf:"bytes,1,rep,name=trades" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradesUpdate) Reset()         { *m = TradesUpdate{} }
func (m *TradesUpdate) String() string { return proto.CompactTextString(m) }
func (*TradesUpdate) ProtoMessage()    {}
func (*TradesUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{7}
}
func (m *TradesUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesUpdate.Unmarshal(m, b)
}
func (m *TradesUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesUpdate.Marshal(b, m, deterministic)
}
func (dst *TradesUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesUpdate.Merge(dst, src)
}
func (m *TradesUpdate) XXX_Size() int {
	return xxx_messageInfo_TradesUpdate.Size(m)
}
func (m *TradesUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TradesUpdate proto.InternalMessageInfo

func (m *TradesUpdate) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

// Interval represents a single OHLC candle.
type Interval struct {
	Closetime      int64          `protobuf:"varint,1,opt,name=closetime" json:"closetime,omitempty"`
	Period         int32          `protobuf:"varint,4,opt,name=period" json:"period,omitempty"`
	Ohlc           *Interval_OHLC `protobuf:"bytes,2,opt,name=ohlc" json:"ohlc,omitempty"`
	VolumeBaseStr  string         `protobuf:"bytes,6,opt,name=volumeBaseStr" json:"volumeBaseStr,omitempty"`
	VolumeQuoteStr string         `protobuf:"bytes,7,opt,name=volumeQuoteStr" json:"volumeQuoteStr,omitempty"`
	// Deprecated
	VolumeBase           float32  `protobuf:"fixed32,3,opt,name=volumeBase" json:"volumeBase,omitempty"`
	VolumeQuote          float32  `protobuf:"fixed32,5,opt,name=volumeQuote" json:"volumeQuote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interval) Reset()         { *m = Interval{} }
func (m *Interval) String() string { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()    {}
func (*Interval) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{8}
}
func (m *Interval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interval.Unmarshal(m, b)
}
func (m *Interval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interval.Marshal(b, m, deterministic)
}
func (dst *Interval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interval.Merge(dst, src)
}
func (m *Interval) XXX_Size() int {
	return xxx_messageInfo_Interval.Size(m)
}
func (m *Interval) XXX_DiscardUnknown() {
	xxx_messageInfo_Interval.DiscardUnknown(m)
}

var xxx_messageInfo_Interval proto.InternalMessageInfo

func (m *Interval) GetClosetime() int64 {
	if m != nil {
		return m.Closetime
	}
	return 0
}

func (m *Interval) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Interval) GetOhlc() *Interval_OHLC {
	if m != nil {
		return m.Ohlc
	}
	return nil
}

func (m *Interval) GetVolumeBaseStr() string {
	if m != nil {
		return m.VolumeBaseStr
	}
	return ""
}

func (m *Interval) GetVolumeQuoteStr() string {
	if m != nil {
		return m.VolumeQuoteStr
	}
	return ""
}

func (m *Interval) GetVolumeBase() float32 {
	if m != nil {
		return m.VolumeBase
	}
	return 0
}

func (m *Interval) GetVolumeQuote() float32 {
	if m != nil {
		return m.VolumeQuote
	}
	return 0
}

type Interval_OHLC struct {
	OpenStr  string `protobuf:"bytes,5,opt,name=openStr" json:"openStr,omitempty"`
	HighStr  string `protobuf:"bytes,6,opt,name=highStr" json:"highStr,omitempty"`
	LowStr   string `protobuf:"bytes,7,opt,name=lowStr" json:"lowStr,omitempty"`
	CloseStr string `protobuf:"bytes,8,opt,name=closeStr" json:"closeStr,omitempty"`
	// Deprecated
	Open                 float32  `protobuf:"fixed32,1,opt,name=open" json:"open,omitempty"`
	High                 float32  `protobuf:"fixed32,2,opt,name=high" json:"high,omitempty"`
	Low                  float32  `protobuf:"fixed32,3,opt,name=low" json:"low,omitempty"`
	Close                float32  `protobuf:"fixed32,4,opt,name=close" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interval_OHLC) Reset()         { *m = Interval_OHLC{} }
func (m *Interval_OHLC) String() string { return proto.CompactTextString(m) }
func (*Interval_OHLC) ProtoMessage()    {}
func (*Interval_OHLC) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{8, 0}
}
func (m *Interval_OHLC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interval_OHLC.Unmarshal(m, b)
}
func (m *Interval_OHLC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interval_OHLC.Marshal(b, m, deterministic)
}
func (dst *Interval_OHLC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interval_OHLC.Merge(dst, src)
}
func (m *Interval_OHLC) XXX_Size() int {
	return xxx_messageInfo_Interval_OHLC.Size(m)
}
func (m *Interval_OHLC) XXX_DiscardUnknown() {
	xxx_messageInfo_Interval_OHLC.DiscardUnknown(m)
}

var xxx_messageInfo_Interval_OHLC proto.InternalMessageInfo

func (m *Interval_OHLC) GetOpenStr() string {
	if m != nil {
		return m.OpenStr
	}
	return ""
}

func (m *Interval_OHLC) GetHighStr() string {
	if m != nil {
		return m.HighStr
	}
	return ""
}

func (m *Interval_OHLC) GetLowStr() string {
	if m != nil {
		return m.LowStr
	}
	return ""
}

func (m *Interval_OHLC) GetCloseStr() string {
	if m != nil {
		return m.CloseStr
	}
	return ""
}

func (m *Interval_OHLC) GetOpen() float32 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Interval_OHLC) GetHigh() float32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Interval_OHLC) GetLow() float32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Interval_OHLC) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

// IntervalsUpdate represents a set of new Intervals (OHLC candles)
type IntervalsUpdate struct {
	Intervals            []*Interval `protobuf:"bytes,1,rep,name=intervals" json:"intervals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IntervalsUpdate) Reset()         { *m = IntervalsUpdate{} }
func (m *IntervalsUpdate) String() string { return proto.CompactTextString(m) }
func (*IntervalsUpdate) ProtoMessage()    {}
func (*IntervalsUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{9}
}
func (m *IntervalsUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntervalsUpdate.Unmarshal(m, b)
}
func (m *IntervalsUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntervalsUpdate.Marshal(b, m, deterministic)
}
func (dst *IntervalsUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntervalsUpdate.Merge(dst, src)
}
func (m *IntervalsUpdate) XXX_Size() int {
	return xxx_messageInfo_IntervalsUpdate.Size(m)
}
func (m *IntervalsUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_IntervalsUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_IntervalsUpdate proto.InternalMessageInfo

func (m *IntervalsUpdate) GetIntervals() []*Interval {
	if m != nil {
		return m.Intervals
	}
	return nil
}

// SummaryUpdate is a market summary update
type SummaryUpdate struct {
	LastStr           string `protobuf:"bytes,10,opt,name=lastStr" json:"lastStr,omitempty"`
	HighStr           string `protobuf:"bytes,11,opt,name=highStr" json:"highStr,omitempty"`
	LowStr            string `protobuf:"bytes,12,opt,name=lowStr" json:"lowStr,omitempty"`
	VolumeBaseStr     string `protobuf:"bytes,13,opt,name=volumeBaseStr" json:"volumeBaseStr,omitempty"`
	VolumeQuoteStr    string `protobuf:"bytes,14,opt,name=volumeQuoteStr" json:"volumeQuoteStr,omitempty"`
	ChangeAbsoluteStr string `protobuf:"bytes,15,opt,name=changeAbsoluteStr" json:"changeAbsoluteStr,omitempty"`
	ChangePercentStr  string `protobuf:"bytes,16,opt,name=changePercentStr" json:"changePercentStr,omitempty"`
	NumTrades         int32  `protobuf:"varint,8,opt,name=numTrades" json:"numTrades,omitempty"`
	// Deprecated
	Last                 float32  `protobuf:"fixed32,2,opt,name=last" json:"last,omitempty"`
	High                 float32  `protobuf:"fixed32,3,opt,name=high" json:"high,omitempty"`
	Low                  float32  `protobuf:"fixed32,4,opt,name=low" json:"low,omitempty"`
	VolumeBase           float32  `protobuf:"fixed32,5,opt,name=volumeBase" json:"volumeBase,omitempty"`
	VolumeQuote          float32  `protobuf:"fixed32,9,opt,name=volumeQuote" json:"volumeQuote,omitempty"`
	ChangeAbsolute       float32  `protobuf:"fixed32,6,opt,name=changeAbsolute" json:"changeAbsolute,omitempty"`
	ChangePercent        float32  `protobuf:"fixed32,7,opt,name=changePercent" json:"changePercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummaryUpdate) Reset()         { *m = SummaryUpdate{} }
func (m *SummaryUpdate) String() string { return proto.CompactTextString(m) }
func (*SummaryUpdate) ProtoMessage()    {}
func (*SummaryUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{10}
}
func (m *SummaryUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryUpdate.Unmarshal(m, b)
}
func (m *SummaryUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryUpdate.Marshal(b, m, deterministic)
}
func (dst *SummaryUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryUpdate.Merge(dst, src)
}
func (m *SummaryUpdate) XXX_Size() int {
	return xxx_messageInfo_SummaryUpdate.Size(m)
}
func (m *SummaryUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryUpdate proto.InternalMessageInfo

func (m *SummaryUpdate) GetLastStr() string {
	if m != nil {
		return m.LastStr
	}
	return ""
}

func (m *SummaryUpdate) GetHighStr() string {
	if m != nil {
		return m.HighStr
	}
	return ""
}

func (m *SummaryUpdate) GetLowStr() string {
	if m != nil {
		return m.LowStr
	}
	return ""
}

func (m *SummaryUpdate) GetVolumeBaseStr() string {
	if m != nil {
		return m.VolumeBaseStr
	}
	return ""
}

func (m *SummaryUpdate) GetVolumeQuoteStr() string {
	if m != nil {
		return m.VolumeQuoteStr
	}
	return ""
}

func (m *SummaryUpdate) GetChangeAbsoluteStr() string {
	if m != nil {
		return m.ChangeAbsoluteStr
	}
	return ""
}

func (m *SummaryUpdate) GetChangePercentStr() string {
	if m != nil {
		return m.ChangePercentStr
	}
	return ""
}

func (m *SummaryUpdate) GetNumTrades() int32 {
	if m != nil {
		return m.NumTrades
	}
	return 0
}

func (m *SummaryUpdate) GetLast() float32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *SummaryUpdate) GetHigh() float32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *SummaryUpdate) GetLow() float32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *SummaryUpdate) GetVolumeBase() float32 {
	if m != nil {
		return m.VolumeBase
	}
	return 0
}

func (m *SummaryUpdate) GetVolumeQuote() float32 {
	if m != nil {
		return m.VolumeQuote
	}
	return 0
}

func (m *SummaryUpdate) GetChangeAbsolute() float32 {
	if m != nil {
		return m.ChangeAbsolute
	}
	return 0
}

func (m *SummaryUpdate) GetChangePercent() float32 {
	if m != nil {
		return m.ChangePercent
	}
	return 0
}

type SparklineUpdate struct {
	Time                 int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	PriceStr             string   `protobuf:"bytes,4,opt,name=priceStr" json:"priceStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SparklineUpdate) Reset()         { *m = SparklineUpdate{} }
func (m *SparklineUpdate) String() string { return proto.CompactTextString(m) }
func (*SparklineUpdate) ProtoMessage()    {}
func (*SparklineUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_market_e4c0778b23f4161b, []int{11}
}
func (m *SparklineUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SparklineUpdate.Unmarshal(m, b)
}
func (m *SparklineUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SparklineUpdate.Marshal(b, m, deterministic)
}
func (dst *SparklineUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SparklineUpdate.Merge(dst, src)
}
func (m *SparklineUpdate) XXX_Size() int {
	return xxx_messageInfo_SparklineUpdate.Size(m)
}
func (m *SparklineUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SparklineUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SparklineUpdate proto.InternalMessageInfo

func (m *SparklineUpdate) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SparklineUpdate) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SparklineUpdate) GetPriceStr() string {
	if m != nil {
		return m.PriceStr
	}
	return ""
}

func init() {
	proto.RegisterType((*Market)(nil), "ProtobufMarkets.Market")
	proto.RegisterType((*Order)(nil), "ProtobufMarkets.Order")
	proto.RegisterType((*Trade)(nil), "ProtobufMarkets.Trade")
	proto.RegisterType((*MarketUpdateMessage)(nil), "ProtobufMarkets.MarketUpdateMessage")
	proto.RegisterType((*OrderBookUpdate)(nil), "ProtobufMarkets.OrderBookUpdate")
	proto.RegisterType((*OrderBookDeltaUpdate)(nil), "ProtobufMarkets.OrderBookDeltaUpdate")
	proto.RegisterType((*OrderBookDeltaUpdate_OrderDeltas)(nil), "ProtobufMarkets.OrderBookDeltaUpdate.OrderDeltas")
	proto.RegisterType((*OrderBookSpreadUpdate)(nil), "ProtobufMarkets.OrderBookSpreadUpdate")
	proto.RegisterType((*TradesUpdate)(nil), "ProtobufMarkets.TradesUpdate")
	proto.RegisterType((*Interval)(nil), "ProtobufMarkets.Interval")
	proto.RegisterType((*Interval_OHLC)(nil), "ProtobufMarkets.Interval.OHLC")
	proto.RegisterType((*IntervalsUpdate)(nil), "ProtobufMarkets.IntervalsUpdate")
	proto.RegisterType((*SummaryUpdate)(nil), "ProtobufMarkets.SummaryUpdate")
	proto.RegisterType((*SparklineUpdate)(nil), "ProtobufMarkets.SparklineUpdate")
}

func init() { proto.RegisterFile("markets/market.proto", fileDescriptor_market_e4c0778b23f4161b) }

var fileDescriptor_market_e4c0778b23f4161b = []byte{
	// 1124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xfe, 0x39, 0xf6, 0x71, 0x12, 0x9b, 0x21, 0x29, 0x4b, 0x04, 0x91, 0xb5, 0x82, 0xca,
	0xaa, 0x2a, 0x57, 0x04, 0x24, 0xee, 0x90, 0x48, 0x5b, 0xe4, 0x44, 0x4d, 0x13, 0x26, 0xe5, 0x0a,
	0x81, 0x34, 0xf6, 0x0e, 0xce, 0xca, 0x6b, 0xaf, 0xd9, 0x9f, 0x94, 0x3e, 0x02, 0xbc, 0x04, 0x2f,
	0xc0, 0x33, 0x70, 0x05, 0x4f, 0xc0, 0x43, 0x70, 0xcd, 0x1b, 0xa0, 0x73, 0x66, 0xbc, 0xde, 0x5d,
	0x7b, 0x9b, 0x82, 0x7a, 0xe5, 0x39, 0xdf, 0x7c, 0xf3, 0xed, 0x9c, 0x9f, 0x99, 0x39, 0x86, 0x83,
	0xb9, 0x88, 0x67, 0x32, 0x4d, 0x1e, 0xa9, 0xdf, 0xe1, 0x32, 0x8e, 0xd2, 0x88, 0x75, 0xaf, 0xf0,
	0x67, 0x9c, 0xfd, 0x70, 0xa1, 0x66, 0xbd, 0xdf, 0x0c, 0x68, 0xaa, 0x31, 0x3b, 0x06, 0x90, 0x3f,
	0x4d, 0x6e, 0xc4, 0x62, 0x2a, 0xcf, 0x7c, 0xd7, 0xea, 0x1b, 0x03, 0x9b, 0x17, 0x10, 0x76, 0x1f,
	0xf6, 0x27, 0x59, 0x1c, 0xcb, 0xc5, 0xe4, 0xd5, 0x95, 0x08, 0xe2, 0x33, 0xdf, 0xb5, 0x89, 0x53,
	0x41, 0xd9, 0x11, 0xb4, 0xd4, 0x37, 0xcf, 0x7c, 0xd7, 0x21, 0x46, 0x6e, 0xe3, 0xdc, 0x4a, 0xd1,
	0x35, 0xfa, 0xc6, 0xa0, 0xcd, 0x73, 0x9b, 0x79, 0xb0, 0x5b, 0x54, 0x72, 0x4d, 0x9a, 0x2f, 0x61,
	0x5e, 0x04, 0xce, 0x65, 0xec, 0xcb, 0x18, 0x85, 0x96, 0x71, 0x30, 0x91, 0xd7, 0x69, 0x4c, 0x5b,
	0x6d, 0xf3, 0xdc, 0x66, 0x1f, 0x40, 0x5b, 0xcc, 0xa3, 0x6c, 0x91, 0xe2, 0xa4, 0x4d, 0x93, 0x6b,
	0x80, 0x1d, 0x80, 0x43, 0x4c, 0xfa, 0xbe, 0xc9, 0x95, 0xc1, 0xee, 0x41, 0x53, 0x51, 0xe8, 0xb3,
	0x26, 0xd7, 0x96, 0xf7, 0x97, 0x09, 0xce, 0x8b, 0x58, 0xf8, 0x52, 0x85, 0x27, 0x95, 0xf1, 0x42,
	0x84, 0x67, 0xbe, 0xdb, 0x21, 0xd9, 0x02, 0x82, 0x5f, 0x4d, 0x83, 0xb9, 0x4c, 0x52, 0x31, 0x5f,
	0x92, 0x88, 0xc5, 0xd7, 0x00, 0x1b, 0x40, 0x37, 0x37, 0x2e, 0x82, 0x30, 0x0c, 0x12, 0x8a, 0x8d,
	0xc5, 0xab, 0x30, 0xfb, 0x08, 0xf6, 0x72, 0xe8, 0xb9, 0x58, 0x44, 0x2e, 0x10, 0xaf, 0x0c, 0x96,
	0xfc, 0x6f, 0xbd, 0xce, 0xff, 0x76, 0xad, 0xff, 0xd6, 0x76, 0xff, 0xed, 0xa2, 0xff, 0xac, 0x0f,
	0x1d, 0x22, 0x3c, 0x89, 0xb2, 0x71, 0x28, 0xdd, 0x66, 0xdf, 0x18, 0x18, 0xbc, 0x08, 0x61, 0xda,
	0x14, 0x57, 0x53, 0x76, 0x88, 0x52, 0xc2, 0xd8, 0x3e, 0x98, 0x81, 0x4f, 0x01, 0xb7, 0xb8, 0x19,
	0xf8, 0xde, 0x2f, 0x0e, 0xbc, 0xab, 0xaa, 0xee, 0x9b, 0xa5, 0x2f, 0x52, 0x79, 0x21, 0x93, 0x44,
	0x4c, 0x25, 0x7b, 0x04, 0x4d, 0x55, 0x2a, 0xb4, 0xed, 0xce, 0xc9, 0x7b, 0xc3, 0x4a, 0xbd, 0x0e,
	0xd5, 0x2f, 0xd7, 0x34, 0xf6, 0x0c, 0xba, 0x11, 0xd6, 0xc3, 0x69, 0x14, 0xcd, 0x94, 0x14, 0x85,
	0xbe, 0x73, 0xd2, 0xdf, 0x58, 0x79, 0x59, 0xe6, 0x8d, 0x1a, 0xbc, 0xba, 0x94, 0x7d, 0x0b, 0x07,
	0x39, 0xf4, 0x44, 0x86, 0xa9, 0xd0, 0x92, 0x16, 0x49, 0x7e, 0x5c, 0x2f, 0x59, 0x20, 0x8f, 0x1a,
	0x7c, 0xab, 0x08, 0xfb, 0x1e, 0x0e, 0x73, 0xfc, 0x7a, 0x19, 0x4b, 0xe1, 0x6b, 0xf5, 0x0e, 0xa9,
	0xdf, 0xaf, 0x57, 0x2f, 0xb2, 0x47, 0x0d, 0xbe, 0x5d, 0x86, 0x3d, 0x86, 0xdd, 0x14, 0x0b, 0x35,
	0xd1, 0xb2, 0x36, 0xc9, 0x7e, 0xb8, 0x21, 0xfb, 0xa2, 0x40, 0x1a, 0x35, 0x78, 0x69, 0x11, 0xc6,
	0x33, 0x58, 0xa4, 0x32, 0xbe, 0x15, 0xe1, 0x4a, 0xc7, 0xa9, 0x89, 0xe7, 0x59, 0x99, 0x87, 0xf1,
	0xac, 0x2c, 0x65, 0x5f, 0xc1, 0x5e, 0x92, 0xcd, 0xe7, 0x22, 0x7e, 0xa5, 0xb5, 0x9a, 0xa4, 0x75,
	0xbc, 0xa1, 0x75, 0x5d, 0x64, 0x8d, 0x1a, 0xbc, 0xbc, 0x0c, 0x77, 0x95, 0x2c, 0x45, 0x3c, 0x0b,
	0x83, 0x85, 0xd4, 0x4a, 0x3b, 0x35, 0xbb, 0xba, 0x2e, 0xf3, 0x70, 0x57, 0x95, 0xa5, 0xa7, 0x2d,
	0x68, 0xaa, 0xd1, 0xb9, 0xdd, 0x6a, 0xf5, 0xda, 0xde, 0xdf, 0x06, 0x74, 0x2b, 0xc5, 0xc1, 0x3e,
	0x83, 0x43, 0x31, 0x9d, 0xc6, 0x72, 0x2a, 0xd2, 0x20, 0x5a, 0x5c, 0x44, 0x7e, 0x16, 0x66, 0xc9,
	0xfa, 0x3a, 0xd9, 0x3e, 0x89, 0x87, 0x28, 0x91, 0x3f, 0x3e, 0xcf, 0xe6, 0x14, 0x34, 0x87, 0x6b,
	0x8b, 0x3d, 0x00, 0x7b, 0x1c, 0xf8, 0x89, 0x6b, 0xf4, 0xad, 0x41, 0xe7, 0xe4, 0xde, 0xf6, 0x4c,
	0x73, 0xe2, 0x20, 0x57, 0x24, 0xb3, 0xc4, 0x35, 0x5f, 0xcf, 0x45, 0x0e, 0x1b, 0x02, 0xdb, 0xdc,
	0x88, 0x3e, 0xd7, 0x5b, 0x66, 0xbc, 0x3f, 0x2c, 0x38, 0xd8, 0x56, 0xb3, 0xff, 0x55, 0xe8, 0x2d,
	0x87, 0xe7, 0x69, 0x1e, 0x1e, 0xcc, 0xe9, 0x27, 0x6f, 0x74, 0xcc, 0x14, 0x48, 0x40, 0xa2, 0x23,
	0xf7, 0x34, 0x8f, 0xdc, 0xff, 0x95, 0xc1, 0xe5, 0x47, 0xbf, 0x1a, 0xd0, 0x29, 0xa0, 0x6c, 0x00,
	0x56, 0x22, 0xd3, 0x3b, 0x72, 0x87, 0x14, 0xf6, 0x10, 0x1c, 0x1f, 0xd7, 0xdc, 0x91, 0x3b, 0x45,
	0x62, 0x47, 0xd0, 0x8c, 0xe5, 0x3c, 0xba, 0xc5, 0xeb, 0xc5, 0x1a, 0x98, 0xa7, 0x66, 0xaf, 0xc1,
	0x35, 0x82, 0x37, 0xb8, 0x1a, 0xa9, 0x98, 0x5a, 0x78, 0x83, 0xe7, 0x80, 0xf7, 0xb3, 0x01, 0x87,
	0x5b, 0x2f, 0x87, 0xf2, 0x1b, 0x64, 0x6c, 0xbe, 0x41, 0xd6, 0x38, 0xf0, 0x75, 0x7c, 0x6a, 0x3d,
	0x19, 0x07, 0x3e, 0x32, 0x45, 0x32, 0xd3, 0xf7, 0x5e, 0x2d, 0x53, 0x24, 0x33, 0xef, 0x0b, 0xd8,
	0x2d, 0x5e, 0x28, 0x6c, 0x08, 0x4d, 0x75, 0xa1, 0xd4, 0x06, 0x8c, 0xe8, 0x5c, 0xb3, 0xbc, 0x3f,
	0x2d, 0x68, 0xad, 0x6e, 0x12, 0xdc, 0xfe, 0x24, 0x8c, 0x12, 0x89, 0x5b, 0x5e, 0x6d, 0x3f, 0x07,
	0xb0, 0x7c, 0x96, 0x32, 0x0e, 0x22, 0xd5, 0x77, 0x38, 0x5c, 0x5b, 0xec, 0x04, 0xec, 0xe8, 0x26,
	0x9c, 0x68, 0xbf, 0x8e, 0x6b, 0x2f, 0xaa, 0xe1, 0xe5, 0xe8, 0xd9, 0x63, 0x4e, 0x5c, 0x7c, 0x64,
	0x6f, 0xa3, 0x30, 0x9b, 0xcb, 0x53, 0x91, 0x50, 0x90, 0x9b, 0x54, 0xb8, 0x65, 0x10, 0x3b, 0x1e,
	0x05, 0x7c, 0x9d, 0x45, 0x29, 0xd1, 0x76, 0x88, 0x56, 0x41, 0xb1, 0x35, 0x58, 0x2f, 0xd4, 0xc7,
	0xa6, 0x80, 0xe0, 0x23, 0x5a, 0x58, 0x41, 0xd5, 0x6f, 0xf2, 0x22, 0x74, 0xf4, 0xbb, 0x01, 0x36,
	0x6e, 0x8f, 0xb9, 0xb0, 0x13, 0x2d, 0xe5, 0x02, 0xbf, 0xe5, 0xd0, 0xb7, 0x56, 0x26, 0xce, 0xdc,
	0x04, 0xd3, 0x9b, 0xf5, 0x66, 0x57, 0x26, 0x06, 0x26, 0x8c, 0x5e, 0xae, 0xb7, 0xa7, 0x2d, 0xec,
	0x11, 0x28, 0x7a, 0x85, 0x1e, 0x61, 0x65, 0x33, 0x06, 0x36, 0x0a, 0xeb, 0x26, 0x88, 0xc6, 0x88,
	0xa1, 0xa4, 0xee, 0x80, 0x68, 0xcc, 0x7a, 0x60, 0x85, 0xd1, 0x4b, 0xed, 0x13, 0x0e, 0xb1, 0x7f,
	0x20, 0x15, 0xdd, 0x28, 0x28, 0xc3, 0x3b, 0x87, 0x6e, 0xe5, 0x41, 0x60, 0x9f, 0x43, 0x3b, 0x7f,
	0x10, 0x74, 0x35, 0xbc, 0x5f, 0x9b, 0x1c, 0xbe, 0xe6, 0x7a, 0xff, 0x58, 0xb0, 0x57, 0x7a, 0x11,
	0xd0, 0xf7, 0x50, 0x24, 0xd4, 0xcf, 0x80, 0xf2, 0x5d, 0x9b, 0xc5, 0xa8, 0x74, 0xea, 0xa2, 0xb2,
	0x5b, 0x8a, 0xca, 0x46, 0xea, 0xf7, 0xde, 0x2c, 0xf5, 0xfb, 0x5b, 0x53, 0xff, 0x10, 0xde, 0x51,
	0xed, 0xeb, 0x97, 0xe3, 0x24, 0x0a, 0x33, 0x45, 0xed, 0x12, 0x75, 0x73, 0x82, 0x3d, 0x80, 0x9e,
	0x02, 0xaf, 0x64, 0x3c, 0x91, 0xaa, 0x41, 0xeb, 0x11, 0x79, 0x03, 0xc7, 0xc3, 0xb0, 0xc8, 0xe6,
	0xea, 0x70, 0x51, 0xfa, 0x1c, 0xbe, 0x06, 0x30, 0x57, 0x18, 0x82, 0x55, 0xae, 0x70, 0x9c, 0xe7,
	0xcf, 0xda, 0xcc, 0x9f, 0xbd, 0xce, 0x5f, 0xb9, 0x58, 0x9d, 0xbb, 0x8a, 0xb5, 0xbd, 0x51, 0xac,
	0xf4, 0x47, 0xa0, 0xe4, 0x1a, 0x15, 0xa4, 0xc9, 0x2b, 0x28, 0x46, 0xba, 0xe4, 0x15, 0x95, 0xa7,
	0xc9, 0xcb, 0xe0, 0xb9, 0xdd, 0x32, 0x7a, 0xa6, 0xf7, 0x1d, 0x74, 0x2b, 0x4f, 0x37, 0xba, 0x43,
	0x17, 0x81, 0xea, 0xa5, 0x69, 0x5c, 0xd3, 0xbc, 0x16, 0x9b, 0x61, 0xbb, 0xdc, 0x0c, 0x2b, 0xf9,
	0x71, 0x93, 0xfe, 0xfe, 0x7c, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x54, 0x28, 0xda,
	0x16, 0x0d, 0x00, 0x00,
}
