// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/client.proto

package ProtobufClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIAuthenticationMessage_Source int32

const (
	APIAuthenticationMessage_UNKNOWN        APIAuthenticationMessage_Source = 0
	APIAuthenticationMessage_GOLANG_SDK     APIAuthenticationMessage_Source = 1
	APIAuthenticationMessage_JAVASCRIPT_SDK APIAuthenticationMessage_Source = 2
	APIAuthenticationMessage_NODE_SDK       APIAuthenticationMessage_Source = 3
	APIAuthenticationMessage_CW_WEB         APIAuthenticationMessage_Source = 4
)

var APIAuthenticationMessage_Source_name = map[int32]string{
	0: "UNKNOWN",
	1: "GOLANG_SDK",
	2: "JAVASCRIPT_SDK",
	3: "NODE_SDK",
	4: "CW_WEB",
}
var APIAuthenticationMessage_Source_value = map[string]int32{
	"UNKNOWN":        0,
	"GOLANG_SDK":     1,
	"JAVASCRIPT_SDK": 2,
	"NODE_SDK":       3,
	"CW_WEB":         4,
}

func (x APIAuthenticationMessage_Source) String() string {
	return proto.EnumName(APIAuthenticationMessage_Source_name, int32(x))
}
func (APIAuthenticationMessage_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{3, 0}
}

// ClientMessage is a wrapper message used to describe the supplied client message
// and pass metadata about the client.
type ClientMessage struct {
	// Types that are valid to be assigned to Body:
	//	*ClientMessage_Identification
	//	*ClientMessage_Subscribe
	//	*ClientMessage_Unsubscribe
	//	*ClientMessage_WebAuthentication
	//	*ClientMessage_ApiAuthentication
	Body                 isClientMessage_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{0}
}
func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (dst *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(dst, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Identification struct {
	Identification *ClientIdentificationMessage `protobuf:"bytes,1,opt,name=identification,oneof"`
}
type ClientMessage_Subscribe struct {
	Subscribe *ClientSubscribeMessage `protobuf:"bytes,2,opt,name=subscribe,oneof"`
}
type ClientMessage_Unsubscribe struct {
	Unsubscribe *ClientUnsubscribeMessage `protobuf:"bytes,3,opt,name=unsubscribe,oneof"`
}
type ClientMessage_WebAuthentication struct {
	WebAuthentication *WebAuthenticationMessage `protobuf:"bytes,4,opt,name=webAuthentication,oneof"`
}
type ClientMessage_ApiAuthentication struct {
	ApiAuthentication *APIAuthenticationMessage `protobuf:"bytes,5,opt,name=apiAuthentication,oneof"`
}

func (*ClientMessage_Identification) isClientMessage_Body()    {}
func (*ClientMessage_Subscribe) isClientMessage_Body()         {}
func (*ClientMessage_Unsubscribe) isClientMessage_Body()       {}
func (*ClientMessage_WebAuthentication) isClientMessage_Body() {}
func (*ClientMessage_ApiAuthentication) isClientMessage_Body() {}

func (m *ClientMessage) GetBody() isClientMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ClientMessage) GetIdentification() *ClientIdentificationMessage {
	if x, ok := m.GetBody().(*ClientMessage_Identification); ok {
		return x.Identification
	}
	return nil
}

func (m *ClientMessage) GetSubscribe() *ClientSubscribeMessage {
	if x, ok := m.GetBody().(*ClientMessage_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *ClientMessage) GetUnsubscribe() *ClientUnsubscribeMessage {
	if x, ok := m.GetBody().(*ClientMessage_Unsubscribe); ok {
		return x.Unsubscribe
	}
	return nil
}

func (m *ClientMessage) GetWebAuthentication() *WebAuthenticationMessage {
	if x, ok := m.GetBody().(*ClientMessage_WebAuthentication); ok {
		return x.WebAuthentication
	}
	return nil
}

func (m *ClientMessage) GetApiAuthentication() *APIAuthenticationMessage {
	if x, ok := m.GetBody().(*ClientMessage_ApiAuthentication); ok {
		return x.ApiAuthentication
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientMessage_OneofMarshaler, _ClientMessage_OneofUnmarshaler, _ClientMessage_OneofSizer, []interface{}{
		(*ClientMessage_Identification)(nil),
		(*ClientMessage_Subscribe)(nil),
		(*ClientMessage_Unsubscribe)(nil),
		(*ClientMessage_WebAuthentication)(nil),
		(*ClientMessage_ApiAuthentication)(nil),
	}
}

func _ClientMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientMessage)
	// body
	switch x := m.Body.(type) {
	case *ClientMessage_Identification:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Identification); err != nil {
			return err
		}
	case *ClientMessage_Subscribe:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Subscribe); err != nil {
			return err
		}
	case *ClientMessage_Unsubscribe:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Unsubscribe); err != nil {
			return err
		}
	case *ClientMessage_WebAuthentication:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WebAuthentication); err != nil {
			return err
		}
	case *ClientMessage_ApiAuthentication:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ApiAuthentication); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientMessage.Body has unexpected type %T", x)
	}
	return nil
}

func _ClientMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientMessage)
	switch tag {
	case 1: // body.identification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientIdentificationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Identification{msg}
		return true, err
	case 2: // body.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientSubscribeMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Subscribe{msg}
		return true, err
	case 3: // body.unsubscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientUnsubscribeMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_Unsubscribe{msg}
		return true, err
	case 4: // body.webAuthentication
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WebAuthenticationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_WebAuthentication{msg}
		return true, err
	case 5: // body.apiAuthentication
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(APIAuthenticationMessage)
		err := b.DecodeMessage(msg)
		m.Body = &ClientMessage_ApiAuthentication{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientMessage)
	// body
	switch x := m.Body.(type) {
	case *ClientMessage_Identification:
		s := proto.Size(x.Identification)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_Subscribe:
		s := proto.Size(x.Subscribe)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_Unsubscribe:
		s := proto.Size(x.Unsubscribe)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_WebAuthentication:
		s := proto.Size(x.WebAuthentication)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientMessage_ApiAuthentication:
		s := proto.Size(x.ApiAuthentication)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ClientIdentificationMessage is the first message sent is from the client to
// the server, identifying itself and the subscriptions it desires.
type ClientIdentificationMessage struct {
	Useragent            string   `protobuf:"bytes,1,opt,name=useragent" json:"useragent,omitempty"`
	Revision             string   `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Integration          string   `protobuf:"bytes,3,opt,name=integration" json:"integration,omitempty"`
	Locale               string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	Subscriptions        []string `protobuf:"bytes,5,rep,name=subscriptions" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIdentificationMessage) Reset()         { *m = ClientIdentificationMessage{} }
func (m *ClientIdentificationMessage) String() string { return proto.CompactTextString(m) }
func (*ClientIdentificationMessage) ProtoMessage()    {}
func (*ClientIdentificationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{1}
}
func (m *ClientIdentificationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIdentificationMessage.Unmarshal(m, b)
}
func (m *ClientIdentificationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIdentificationMessage.Marshal(b, m, deterministic)
}
func (dst *ClientIdentificationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIdentificationMessage.Merge(dst, src)
}
func (m *ClientIdentificationMessage) XXX_Size() int {
	return xxx_messageInfo_ClientIdentificationMessage.Size(m)
}
func (m *ClientIdentificationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIdentificationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIdentificationMessage proto.InternalMessageInfo

func (m *ClientIdentificationMessage) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *ClientIdentificationMessage) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ClientIdentificationMessage) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

func (m *ClientIdentificationMessage) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *ClientIdentificationMessage) GetSubscriptions() []string {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type WebAuthenticationMessage struct {
	Identification       *ClientIdentificationMessage `protobuf:"bytes,1,opt,name=identification" json:"identification,omitempty"`
	Token                string                       `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Nonce                string                       `protobuf:"bytes,3,opt,name=nonce" json:"nonce,omitempty"`
	AccessList           []string                     `protobuf:"bytes,4,rep,name=access_list,json=accessList" json:"access_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *WebAuthenticationMessage) Reset()         { *m = WebAuthenticationMessage{} }
func (m *WebAuthenticationMessage) String() string { return proto.CompactTextString(m) }
func (*WebAuthenticationMessage) ProtoMessage()    {}
func (*WebAuthenticationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{2}
}
func (m *WebAuthenticationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebAuthenticationMessage.Unmarshal(m, b)
}
func (m *WebAuthenticationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebAuthenticationMessage.Marshal(b, m, deterministic)
}
func (dst *WebAuthenticationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebAuthenticationMessage.Merge(dst, src)
}
func (m *WebAuthenticationMessage) XXX_Size() int {
	return xxx_messageInfo_WebAuthenticationMessage.Size(m)
}
func (m *WebAuthenticationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebAuthenticationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebAuthenticationMessage proto.InternalMessageInfo

func (m *WebAuthenticationMessage) GetIdentification() *ClientIdentificationMessage {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *WebAuthenticationMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WebAuthenticationMessage) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *WebAuthenticationMessage) GetAccessList() []string {
	if m != nil {
		return m.AccessList
	}
	return nil
}

type APIAuthenticationMessage struct {
	Token                string                          `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Nonce                string                          `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	ApiKey               string                          `protobuf:"bytes,3,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	Source               APIAuthenticationMessage_Source `protobuf:"varint,4,opt,name=source,enum=ProtobufClient.APIAuthenticationMessage_Source" json:"source,omitempty"`
	Version              string                          `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	Subscriptions        []string                        `protobuf:"bytes,6,rep,name=subscriptions" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *APIAuthenticationMessage) Reset()         { *m = APIAuthenticationMessage{} }
func (m *APIAuthenticationMessage) String() string { return proto.CompactTextString(m) }
func (*APIAuthenticationMessage) ProtoMessage()    {}
func (*APIAuthenticationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{3}
}
func (m *APIAuthenticationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIAuthenticationMessage.Unmarshal(m, b)
}
func (m *APIAuthenticationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIAuthenticationMessage.Marshal(b, m, deterministic)
}
func (dst *APIAuthenticationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIAuthenticationMessage.Merge(dst, src)
}
func (m *APIAuthenticationMessage) XXX_Size() int {
	return xxx_messageInfo_APIAuthenticationMessage.Size(m)
}
func (m *APIAuthenticationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_APIAuthenticationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_APIAuthenticationMessage proto.InternalMessageInfo

func (m *APIAuthenticationMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *APIAuthenticationMessage) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *APIAuthenticationMessage) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *APIAuthenticationMessage) GetSource() APIAuthenticationMessage_Source {
	if m != nil {
		return m.Source
	}
	return APIAuthenticationMessage_UNKNOWN
}

func (m *APIAuthenticationMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *APIAuthenticationMessage) GetSubscriptions() []string {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type ClientSessionMessage struct {
	// Types that are valid to be assigned to SessionConfig:
	//	*ClientSessionMessage_Session_
	//	*ClientSessionMessage_AnonymousTradingSession_
	SessionConfig        isClientSessionMessage_SessionConfig `protobuf_oneof:"SessionConfig"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ClientSessionMessage) Reset()         { *m = ClientSessionMessage{} }
func (m *ClientSessionMessage) String() string { return proto.CompactTextString(m) }
func (*ClientSessionMessage) ProtoMessage()    {}
func (*ClientSessionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{4}
}
func (m *ClientSessionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSessionMessage.Unmarshal(m, b)
}
func (m *ClientSessionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSessionMessage.Marshal(b, m, deterministic)
}
func (dst *ClientSessionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSessionMessage.Merge(dst, src)
}
func (m *ClientSessionMessage) XXX_Size() int {
	return xxx_messageInfo_ClientSessionMessage.Size(m)
}
func (m *ClientSessionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSessionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSessionMessage proto.InternalMessageInfo

type isClientSessionMessage_SessionConfig interface {
	isClientSessionMessage_SessionConfig()
}

type ClientSessionMessage_Session_ struct {
	Session *ClientSessionMessage_Session `protobuf:"bytes,1,opt,name=session,oneof"`
}
type ClientSessionMessage_AnonymousTradingSession_ struct {
	AnonymousTradingSession *ClientSessionMessage_AnonymousTradingSession `protobuf:"bytes,2,opt,name=anonymousTradingSession,oneof"`
}

func (*ClientSessionMessage_Session_) isClientSessionMessage_SessionConfig()                 {}
func (*ClientSessionMessage_AnonymousTradingSession_) isClientSessionMessage_SessionConfig() {}

func (m *ClientSessionMessage) GetSessionConfig() isClientSessionMessage_SessionConfig {
	if m != nil {
		return m.SessionConfig
	}
	return nil
}

func (m *ClientSessionMessage) GetSession() *ClientSessionMessage_Session {
	if x, ok := m.GetSessionConfig().(*ClientSessionMessage_Session_); ok {
		return x.Session
	}
	return nil
}

func (m *ClientSessionMessage) GetAnonymousTradingSession() *ClientSessionMessage_AnonymousTradingSession {
	if x, ok := m.GetSessionConfig().(*ClientSessionMessage_AnonymousTradingSession_); ok {
		return x.AnonymousTradingSession
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientSessionMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientSessionMessage_OneofMarshaler, _ClientSessionMessage_OneofUnmarshaler, _ClientSessionMessage_OneofSizer, []interface{}{
		(*ClientSessionMessage_Session_)(nil),
		(*ClientSessionMessage_AnonymousTradingSession_)(nil),
	}
}

func _ClientSessionMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientSessionMessage)
	// SessionConfig
	switch x := m.SessionConfig.(type) {
	case *ClientSessionMessage_Session_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Session); err != nil {
			return err
		}
	case *ClientSessionMessage_AnonymousTradingSession_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AnonymousTradingSession); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientSessionMessage.SessionConfig has unexpected type %T", x)
	}
	return nil
}

func _ClientSessionMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientSessionMessage)
	switch tag {
	case 1: // SessionConfig.session
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientSessionMessage_Session)
		err := b.DecodeMessage(msg)
		m.SessionConfig = &ClientSessionMessage_Session_{msg}
		return true, err
	case 2: // SessionConfig.anonymousTradingSession
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClientSessionMessage_AnonymousTradingSession)
		err := b.DecodeMessage(msg)
		m.SessionConfig = &ClientSessionMessage_AnonymousTradingSession_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientSessionMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientSessionMessage)
	// SessionConfig
	switch x := m.SessionConfig.(type) {
	case *ClientSessionMessage_Session_:
		s := proto.Size(x.Session)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientSessionMessage_AnonymousTradingSession_:
		s := proto.Size(x.AnonymousTradingSession)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ClientSessionMessage_Session struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Expires              int64    `protobuf:"varint,2,opt,name=expires" json:"expires,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	MfaToken             string   `protobuf:"bytes,4,opt,name=mfaToken" json:"mfaToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSessionMessage_Session) Reset()         { *m = ClientSessionMessage_Session{} }
func (m *ClientSessionMessage_Session) String() string { return proto.CompactTextString(m) }
func (*ClientSessionMessage_Session) ProtoMessage()    {}
func (*ClientSessionMessage_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{4, 0}
}
func (m *ClientSessionMessage_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSessionMessage_Session.Unmarshal(m, b)
}
func (m *ClientSessionMessage_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSessionMessage_Session.Marshal(b, m, deterministic)
}
func (dst *ClientSessionMessage_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSessionMessage_Session.Merge(dst, src)
}
func (m *ClientSessionMessage_Session) XXX_Size() int {
	return xxx_messageInfo_ClientSessionMessage_Session.Size(m)
}
func (m *ClientSessionMessage_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSessionMessage_Session.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSessionMessage_Session proto.InternalMessageInfo

func (m *ClientSessionMessage_Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ClientSessionMessage_Session) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *ClientSessionMessage_Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ClientSessionMessage_Session) GetMfaToken() string {
	if m != nil {
		return m.MfaToken
	}
	return ""
}

type ClientSessionMessage_AnonymousTradingSession struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Expiration           int64    `protobuf:"varint,3,opt,name=expiration" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSessionMessage_AnonymousTradingSession) Reset() {
	*m = ClientSessionMessage_AnonymousTradingSession{}
}
func (m *ClientSessionMessage_AnonymousTradingSession) String() string {
	return proto.CompactTextString(m)
}
func (*ClientSessionMessage_AnonymousTradingSession) ProtoMessage() {}
func (*ClientSessionMessage_AnonymousTradingSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{4, 1}
}
func (m *ClientSessionMessage_AnonymousTradingSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession.Unmarshal(m, b)
}
func (m *ClientSessionMessage_AnonymousTradingSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession.Marshal(b, m, deterministic)
}
func (dst *ClientSessionMessage_AnonymousTradingSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession.Merge(dst, src)
}
func (m *ClientSessionMessage_AnonymousTradingSession) XXX_Size() int {
	return xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession.Size(m)
}
func (m *ClientSessionMessage_AnonymousTradingSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSessionMessage_AnonymousTradingSession proto.InternalMessageInfo

func (m *ClientSessionMessage_AnonymousTradingSession) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ClientSessionMessage_AnonymousTradingSession) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ClientSessionMessage_AnonymousTradingSession) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// SubscribeMessage informs the Stream Hub to subscribe the current web socket to
// the supplied channel.
type ClientSubscribeMessage struct {
	SubscriptionKeys     []string `protobuf:"bytes,1,rep,name=subscriptionKeys" json:"subscriptionKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSubscribeMessage) Reset()         { *m = ClientSubscribeMessage{} }
func (m *ClientSubscribeMessage) String() string { return proto.CompactTextString(m) }
func (*ClientSubscribeMessage) ProtoMessage()    {}
func (*ClientSubscribeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{5}
}
func (m *ClientSubscribeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSubscribeMessage.Unmarshal(m, b)
}
func (m *ClientSubscribeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSubscribeMessage.Marshal(b, m, deterministic)
}
func (dst *ClientSubscribeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSubscribeMessage.Merge(dst, src)
}
func (m *ClientSubscribeMessage) XXX_Size() int {
	return xxx_messageInfo_ClientSubscribeMessage.Size(m)
}
func (m *ClientSubscribeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSubscribeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSubscribeMessage proto.InternalMessageInfo

func (m *ClientSubscribeMessage) GetSubscriptionKeys() []string {
	if m != nil {
		return m.SubscriptionKeys
	}
	return nil
}

// UnsubscribeMessage informs the Stream Hub to unsubscribe the current web socket
// from the supplied channel.
type ClientUnsubscribeMessage struct {
	SubscriptionKeys     []string `protobuf:"bytes,1,rep,name=subscriptionKeys" json:"subscriptionKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientUnsubscribeMessage) Reset()         { *m = ClientUnsubscribeMessage{} }
func (m *ClientUnsubscribeMessage) String() string { return proto.CompactTextString(m) }
func (*ClientUnsubscribeMessage) ProtoMessage()    {}
func (*ClientUnsubscribeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_4f9d92b30dd5a261, []int{6}
}
func (m *ClientUnsubscribeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientUnsubscribeMessage.Unmarshal(m, b)
}
func (m *ClientUnsubscribeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientUnsubscribeMessage.Marshal(b, m, deterministic)
}
func (dst *ClientUnsubscribeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientUnsubscribeMessage.Merge(dst, src)
}
func (m *ClientUnsubscribeMessage) XXX_Size() int {
	return xxx_messageInfo_ClientUnsubscribeMessage.Size(m)
}
func (m *ClientUnsubscribeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientUnsubscribeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientUnsubscribeMessage proto.InternalMessageInfo

func (m *ClientUnsubscribeMessage) GetSubscriptionKeys() []string {
	if m != nil {
		return m.SubscriptionKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientMessage)(nil), "ProtobufClient.ClientMessage")
	proto.RegisterType((*ClientIdentificationMessage)(nil), "ProtobufClient.ClientIdentificationMessage")
	proto.RegisterType((*WebAuthenticationMessage)(nil), "ProtobufClient.WebAuthenticationMessage")
	proto.RegisterType((*APIAuthenticationMessage)(nil), "ProtobufClient.APIAuthenticationMessage")
	proto.RegisterType((*ClientSessionMessage)(nil), "ProtobufClient.ClientSessionMessage")
	proto.RegisterType((*ClientSessionMessage_Session)(nil), "ProtobufClient.ClientSessionMessage.Session")
	proto.RegisterType((*ClientSessionMessage_AnonymousTradingSession)(nil), "ProtobufClient.ClientSessionMessage.AnonymousTradingSession")
	proto.RegisterType((*ClientSubscribeMessage)(nil), "ProtobufClient.ClientSubscribeMessage")
	proto.RegisterType((*ClientUnsubscribeMessage)(nil), "ProtobufClient.ClientUnsubscribeMessage")
	proto.RegisterEnum("ProtobufClient.APIAuthenticationMessage_Source", APIAuthenticationMessage_Source_name, APIAuthenticationMessage_Source_value)
}

func init() { proto.RegisterFile("client/client.proto", fileDescriptor_client_4f9d92b30dd5a261) }

var fileDescriptor_client_4f9d92b30dd5a261 = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xe3, 0x38, 0x75, 0x9a, 0xc9, 0xd3, 0x3c, 0x61, 0xa9, 0x5a, 0x2b, 0x20, 0xa8, 0x2c,
	0x84, 0x2a, 0x40, 0xa9, 0x54, 0xae, 0x5c, 0xd2, 0xf4, 0x25, 0x21, 0x25, 0xad, 0x9c, 0x96, 0x70,
	0x8b, 0xd6, 0xce, 0xc6, 0x5d, 0x35, 0x5d, 0x5b, 0x5e, 0xbb, 0x34, 0x9f, 0x0c, 0x0e, 0x70, 0xe6,
	0x6b, 0x21, 0xaf, 0xd7, 0xb5, 0xd3, 0xd8, 0xa8, 0x48, 0x9c, 0x9c, 0xff, 0xec, 0xcc, 0x6f, 0x67,
	0x77, 0x66, 0x36, 0xf0, 0xd4, 0x9e, 0x53, 0xc2, 0x82, 0xbd, 0xf8, 0xd3, 0xf6, 0x7c, 0x37, 0x70,
	0x51, 0xe3, 0x3c, 0xfa, 0x58, 0xe1, 0xac, 0x2b, 0xac, 0xc6, 0x77, 0x15, 0x36, 0xe2, 0x9f, 0x9f,
	0x08, 0xe7, 0xd8, 0x21, 0xe8, 0x12, 0x1a, 0x74, 0x4a, 0x58, 0x40, 0x67, 0xd4, 0xc6, 0x01, 0x75,
	0x99, 0xae, 0xec, 0x28, 0xbb, 0xf5, 0xfd, 0xb7, 0xed, 0xe5, 0xd0, 0x76, 0xfc, 0xe9, 0x2f, 0xf9,
	0x4a, 0x48, 0xaf, 0x64, 0x3e, 0x80, 0xa0, 0x63, 0xa8, 0xf1, 0xd0, 0xe2, 0xb6, 0x4f, 0x2d, 0xa2,
	0x97, 0x05, 0xf1, 0x75, 0x3e, 0x71, 0x94, 0xb8, 0xa5, 0xb0, 0x34, 0x14, 0x9d, 0x42, 0x3d, 0x64,
	0x29, 0x49, 0x15, 0xa4, 0xdd, 0x7c, 0xd2, 0x65, 0xea, 0x98, 0xb2, 0xb2, 0xe1, 0xe8, 0x0b, 0x3c,
	0xf9, 0x4a, 0xac, 0x4e, 0x18, 0x5c, 0x45, 0xc9, 0xca, 0xf3, 0x56, 0xf2, 0x99, 0xe3, 0x87, 0x8e,
	0x29, 0x73, 0x15, 0x12, 0x91, 0xb1, 0x47, 0x1f, 0x90, 0xd7, 0xf2, 0xc9, 0x9d, 0xf3, 0x7e, 0x21,
	0x79, 0x05, 0x72, 0xa0, 0x41, 0xc5, 0x72, 0xa7, 0x0b, 0xe3, 0x9b, 0x02, 0xcf, 0xfe, 0x50, 0x03,
	0xf4, 0x1c, 0x6a, 0x21, 0x27, 0x3e, 0x76, 0x08, 0x0b, 0x44, 0x0d, 0x6b, 0x66, 0x6a, 0x40, 0x2d,
	0x58, 0xf7, 0xc9, 0x2d, 0xe5, 0x51, 0x5a, 0x65, 0xb1, 0x78, 0xaf, 0xd1, 0x0e, 0xd4, 0x29, 0x0b,
	0x88, 0xe3, 0xc7, 0x59, 0xab, 0x62, 0x39, 0x6b, 0x42, 0x5b, 0xa0, 0xcd, 0x5d, 0x1b, 0xcf, 0x89,
	0xb8, 0xac, 0x9a, 0x29, 0x15, 0x7a, 0x05, 0x1b, 0xf2, 0x72, 0xbd, 0xc8, 0x8f, 0xeb, 0x6b, 0x3b,
	0xea, 0x6e, 0xcd, 0x5c, 0x36, 0x1a, 0x3f, 0x14, 0xd0, 0x8b, 0x6e, 0x13, 0x8d, 0xfe, 0x41, 0xff,
	0xad, 0x74, 0xdf, 0x26, 0xac, 0x05, 0xee, 0x35, 0x49, 0x8e, 0x1a, 0x8b, 0xc8, 0xca, 0x5c, 0x66,
	0x13, 0x79, 0xc2, 0x58, 0xa0, 0x97, 0x50, 0xc7, 0xb6, 0x4d, 0x38, 0x9f, 0xcc, 0x29, 0x0f, 0xf4,
	0x8a, 0x38, 0x01, 0xc4, 0xa6, 0x53, 0xca, 0x03, 0xe3, 0x67, 0x19, 0xf4, 0xa2, 0x92, 0xa5, 0x3b,
	0x29, 0xb9, 0x3b, 0x95, 0xb3, 0x3b, 0x6d, 0x43, 0x15, 0x7b, 0x74, 0x72, 0x4d, 0x16, 0x32, 0x03,
	0x0d, 0x7b, 0x74, 0x40, 0x16, 0xe8, 0x04, 0x34, 0xee, 0x86, 0xbe, 0x1d, 0x5f, 0x6f, 0x63, 0x7f,
	0xef, 0xb1, 0x1d, 0xd3, 0x1e, 0x89, 0x30, 0x53, 0x86, 0x23, 0x1d, 0xaa, 0xb7, 0xc4, 0xe7, 0x49,
	0xef, 0xd5, 0xcc, 0x44, 0xae, 0x56, 0x4a, 0xcb, 0xab, 0xd4, 0x08, 0xb4, 0x98, 0x88, 0xea, 0x50,
	0xbd, 0x1c, 0x0e, 0x86, 0x67, 0xe3, 0x61, 0xb3, 0x84, 0x1a, 0x00, 0x27, 0x67, 0xa7, 0x9d, 0xe1,
	0xc9, 0x64, 0x74, 0x38, 0x68, 0x2a, 0x08, 0x41, 0xe3, 0x63, 0xe7, 0x73, 0x67, 0xd4, 0x35, 0xfb,
	0xe7, 0x17, 0xc2, 0x56, 0x46, 0xff, 0xc1, 0xfa, 0xf0, 0xec, 0xf0, 0x48, 0x28, 0x15, 0x01, 0x68,
	0xdd, 0xf1, 0x64, 0x7c, 0x74, 0xd0, 0xac, 0x18, 0xbf, 0x54, 0xd8, 0x94, 0xa3, 0x4e, 0x38, 0xcf,
	0xdc, 0x5d, 0x0f, 0xaa, 0x3c, 0xb6, 0xc8, 0x9a, 0xbf, 0x2b, 0x78, 0x21, 0x96, 0xc2, 0xda, 0x52,
	0xf6, 0x4a, 0x66, 0x12, 0x8e, 0xee, 0x60, 0x1b, 0x33, 0x97, 0x2d, 0x6e, 0xdc, 0x90, 0x5f, 0xf8,
	0x78, 0x4a, 0x99, 0x23, 0xbd, 0xe4, 0xdb, 0xf3, 0xe1, 0x51, 0xe4, 0x4e, 0x3e, 0xa3, 0x57, 0x32,
	0x8b, 0xf0, 0xad, 0x1b, 0xa8, 0xca, 0x9f, 0xd1, 0x90, 0x44, 0xf3, 0xd6, 0x9f, 0xca, 0x5e, 0x90,
	0x2a, 0x2a, 0x0a, 0xb9, 0xf3, 0xa8, 0x4f, 0xb8, 0x48, 0x46, 0x35, 0x13, 0x99, 0x36, 0x8f, 0x9a,
	0x6d, 0x9e, 0x16, 0xac, 0xdf, 0xcc, 0xf0, 0x85, 0x58, 0x88, 0xc7, 0xed, 0x5e, 0xb7, 0xae, 0x61,
	0xbb, 0x20, 0xc9, 0x28, 0x8c, 0xdc, 0xd9, 0x57, 0x98, 0x39, 0x44, 0x26, 0x70, 0xaf, 0x0b, 0xe6,
	0xe1, 0x05, 0x80, 0xc8, 0x24, 0x1d, 0x7b, 0xd5, 0xcc, 0x58, 0x0e, 0xfe, 0x87, 0x0d, 0x09, 0xef,
	0xba, 0x6c, 0x46, 0x1d, 0xe3, 0x10, 0xb6, 0xf2, 0xdf, 0x6c, 0xf4, 0x06, 0x9a, 0xd9, 0x4e, 0x1a,
	0x90, 0x05, 0xd7, 0x15, 0xd1, 0x61, 0x2b, 0x76, 0xe3, 0x18, 0xf4, 0xa2, 0xf7, 0xfa, 0x6f, 0x38,
	0x96, 0x26, 0xfe, 0xe2, 0xde, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x96, 0x4e, 0x00, 0x06, 0xf9,
	0x06, 0x00, 0x00,
}
